// Core / misc — stability and compression (sit-ups → L-sit → V-sit → manna; flags).
import { S } from "./def.js";

const C = "core";
export default [
  S("situp", "Sit-up", C, "F", {
    ttl: "a few days",
    muscles: "Abs, hip flexors",
    strain: "Lower back, neck",
    desc: "Lying on your back and curling up to sitting. A simple starting point for core strength.",
    steps: ["Lie on your back, knees bent, feet flat.", "Brace the stomach and curl up, rib by rib.", "Sit fully up.", "Lower slowly."],
    good: ["Controlled up and down", "Neck relaxed", "Feet stay down"],
    bad: ["Yanking on the neck", "Dropping back down", "Using momentum"],
    main: ["Sit-ups"],
    acc: ["Dead bugs", "Planks"],
    yt: [["Sit up proper form"]],
  }),
  S("hollow", "Hollow Body Hold", C, "E", {
    pre: ["situp"],
    hold: true,
    ttl: "1–2 weeks",
    muscles: "Abs, hip flexors",
    strain: "Lower back",
    desc: "Lower back pressed into the floor with arms and legs held just off it — the body shape behind handstands, levers and planche. WINGS' foundation goal: 30 seconds.",
    steps: ["Lie on your back, press the lower back into the floor.", "Lift shoulders and legs a little off the floor.", "Reach the arms overhead by the ears.", "Bend the knees to make it easier."],
    good: ["Lower back flat to the floor", "Ribs pulled down", "Long body"],
    bad: ["Lower back arching up", "Legs too high", "Straining the neck"],
    main: ["Hollow body holds (aim for 30 s)", "Hollow rocks"],
    acc: ["Dead bugs", "Sit-ups"],
    yt: [["Hollow body hold tutorial"]],
  }),
  S("lsitcomp", "L-sit Compression", C, "D", {
    pre: ["hollow"],
    ttl: "2–4 weeks",
    muscles: "Hip flexors, abs, quads",
    strain: "Hip flexors",
    desc: "Seated leg lifts with straight legs and hands beside the knees — trains the compression strength the L-sit, V-sit and presses need.",
    steps: ["Sit with legs straight, hands by the knees or hips.", "Lean slightly forward.", "Lift both heels off the floor without using the hands.", "Hold briefly, lower slowly. Count reps."],
    good: ["Legs straight", "Toes pointed", "Slow lifts"],
    bad: ["Leaning back", "Bent knees", "Swinging"],
    main: ["Seated leg lifts"],
    acc: ["Hollow body hold", "Pike stretch"],
    yt: [["L sit compression drills"]],
  }),
  S("lsit", "L-sit", C, "D", {
    pre: ["lsitcomp"],
    hold: true,
    ttl: "1–2 months",
    muscles: "Abs, hip flexors, quads, triceps",
    strain: "Wrists",
    desc: "Supporting yourself on straight arms with straight legs out in front, parallel to the floor. WINGS' foundation goal: 20 seconds. Tuck it first if needed.",
    steps: ["Hands on parallettes or the floor beside the hips.", "Push down, lock the arms, depress the shoulders.", "Lift the legs (tucked first, then one leg, then both straight).", "Hold."],
    good: ["Legs straight and level", "Arms locked", "Shoulders pushed down"],
    bad: ["Legs drooping", "Bent knees", "Shrugging"],
    main: ["L-sit holds (aim for 20 s)", "Tuck L-sit"],
    acc: ["L-sit compression", "Support hold"],
    yt: [["L sit tutorial beginners"]],
  }),
  S("dragonflag", "Dragon Flag", C, "B", {
    pre: ["hollow"],
    ttl: "2–4 months",
    muscles: "Abs, lats, whole core",
    strain: "Lower back, neck",
    desc: "Lying on a bench holding behind your head and lowering a rigid body with only the shoulders touching. WINGS uses it as a front lever accessory.",
    steps: ["Lie on a bench, grip behind the head.", "Lift the body so only the upper back touches.", "Lower slowly as one straight line.", "Start with tucked or negative-only reps."],
    good: ["Body rigid and straight", "Slow lowering", "Hips don't bend"],
    bad: ["Piking", "Arching the lower back", "Dropping"],
    main: ["Dragon flag negatives", "Tuck dragon flags"],
    acc: ["Hollow body hold", "Sit-ups"],
    yt: [["Dragon flag tutorial progression"]],
  }),
  S("vsit", "V-sit", C, "A", {
    pre: ["lsit"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Abs, hip flexors, triceps, shoulders",
    strain: "Wrists, shoulders",
    desc: "An L-sit with the legs raised well above horizontal into a V. Needs strong compression and flexibility.",
    steps: ["From an L-sit, lean the shoulders back slightly.", "Raise the legs higher toward the face.", "Push the hands hard into the floor.", "Hold."],
    good: ["Legs above horizontal", "Locked arms", "Shoulders pushed down"],
    bad: ["Bent knees", "Collapsing on the hands", "Holding the breath"],
    main: ["V-sit holds", "High L-sit"],
    acc: ["L-sit compression", "Pike stretch"],
    yt: [["V sit tutorial progression"]],
  }),
  S("isit", "I-sit", C, "S", {
    pre: ["vsit"],
    hold: true,
    ttl: "1+ year",
    muscles: "Abs, hip flexors, shoulders",
    strain: "Shoulders, wrists",
    desc: "A V-sit pushed so far that the legs point straight up — body folded into an I.",
    steps: ["Build a high V-sit.", "Push the hips forward and the shoulders back.", "Bring the legs vertical.", "Hold."],
    good: ["Legs vertical", "Locked arms", "Strong push through the hands"],
    bad: ["Bent knees", "Sinking shoulders", "Forcing flexibility"],
    main: ["High V-sit holds"],
    acc: ["Compression drills", "Shoulder extension stretches"],
    yt: [["I sit calisthenics"]],
  }),
  S("manna", "Manna", C, "S", {
    pre: ["isit"],
    hold: true,
    ttl: "Years",
    muscles: "Shoulders (extension), abs, triceps",
    strain: "Shoulders, wrists",
    desc: "Hands behind the hips and legs past vertical, the body folded with the hips pushed far forward — an elite compression hold.",
    steps: ["Hands behind you, fingers back.", "From a high V / I-sit, push the hips forward past the hands.", "Lift the legs past vertical.", "Hold."],
    good: ["Arms locked", "Huge compression", "Shoulders depressed"],
    bad: ["Rushing shoulder flexibility", "Bent arms", "Skipping prerequisites"],
    main: ["Manna progressions"],
    acc: ["V-sit / I-sit", "Shoulder extension mobility"],
    yt: [["Manna calisthenics progression"]],
  }),
  S("humanflag", "Human Flag", C, "A", {
    pre: ["dragonflag"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Obliques, lats, shoulders",
    strain: "Shoulders, wrists",
    desc: "Holding your body out sideways from a vertical pole, like a flag.",
    steps: ["Grip a vertical pole, top hand pulling, bottom hand pushing.", "Lock both arms.", "Kick up and hold sideways (tuck first).", "Extend the legs over time."],
    good: ["Bottom arm locked and pushing", "Hips stacked", "Body straight"],
    bad: ["Bent bottom arm", "Hips sagging", "Hands too close"],
    main: ["Tuck human flag", "Vertical flag"],
    acc: ["Side plank", "Dragon flag"],
    yt: [["Human flag tutorial progression"]],
  }),
  S("victorian", "Victorian", C, "S", {
    pre: ["humanflag"],
    hold: true,
    ttl: "Years",
    muscles: "Biceps, chest, shoulders, core",
    strain: "Biceps tendon, shoulders",
    desc: "A face-down horizontal hold with straight arms forward of the body (usually on rings) — one of the rarest strength holds.",
    steps: ["Build strong back lever and front lever foundations.", "Practise Victorian leans on rings or a bar.", "Progress tuck → straddle.", "Hold with locked arms."],
    good: ["Locked arms", "Level body", "Patient progression"],
    bad: ["Bent arms", "Ignoring tendon pain", "Skipping prerequisites"],
    main: ["Tuck Victorian holds"],
    acc: ["Back lever", "Front lever"],
    yt: [["Victorian calisthenics hold"]],
  }),
];
