// Horizontal pull — body parallel to the ground (rows → front lever).
import { S } from "./def.js";

const C = "hpull";
export default [
  S("inclinerow", "Assisted Inverted Row", C, "F", {
    ttl: "~1 week",
    muscles: "Upper back, rear shoulders, biceps",
    strain: "Elbows",
    desc: "Rows with the body more upright — a high bar, table edge or rings with the feet close. The start of all rowing.",
    steps: ["Hold a chest-height bar and walk the feet forward so you lean back.", "Keep a straight line from head to heels.", "Pull the chest to the bar, squeezing the shoulder blades together.", "Lower with control. Walk the feet forward to make it harder."],
    good: ["Body straight", "Chest to the bar", "Shoulder blades squeeze back"],
    bad: ["Hips sagging", "Pulling only with the arms", "Shrugging"],
    main: ["Incline rows", "Ring rows"],
    acc: ["Scapula retractions", "Dead hang"],
    yt: [["Incline row bodyweight beginner"]],
  }),
  S("austrow", "Inverted Row", C, "E", {
    pre: ["inclinerow"],
    ttl: "2–3 weeks",
    muscles: "Upper back, lats, biceps",
    strain: "Elbows",
    desc: "A bodyweight row under a waist-height bar with the body nearly horizontal. WINGS' foundation goal: 20 reps (also a front lever prerequisite).",
    steps: ["Hang under a waist-height bar, body straight, heels down.", "Pull the chest to the bar.", "Pause and squeeze the back.", "Lower to straight arms."],
    good: ["Rigid plank body", "Chest touches the bar", "Full extension at the bottom"],
    bad: ["Piking at the hips", "Half reps", "Head reaching for the bar"],
    main: ["Inverted rows (aim for 20)"],
    acc: ["Scapula pulls", "Face pulls (band)"],
    yt: [["Australian pull up row tutorial"]],
  }),
  S("tuckfl", "Tuck FL", C, "D", {
    pre: ["austrow"],
    hold: true,
    ttl: "1–2 months",
    muscles: "Lats, core, rear shoulders, triceps",
    strain: "Elbows, shoulders",
    desc: "Front lever stage I: hanging face-up with the back horizontal and knees tucked, arms straight. WINGS' goal is 15+ seconds before moving on. Prerequisites: ~10–15 pull-ups and 20 rows.",
    steps: ["Hang from a bar, pull the shoulders down and back (retract).", "Tuck the knees and rotate back until the back is flat and horizontal.", "Press the bar toward the hips with straight arms.", "Hold — build to 15+ s."],
    good: ["Straight arms", "Scapula retracted", "Back parallel to the floor"],
    bad: ["Hips too low", "Bent elbows", "Shrugged shoulders"],
    main: ["Tuck front lever holds"],
    acc: ["Scapula pull-ups", "Pull-ups"],
    yt: [["Tuck front lever tutorial"]],
  }),
  S("tuckflrow", "Tuck FL Row", C, "C", {
    pre: ["tuckfl"],
    ttl: "1–2 months",
    muscles: "Lats, upper back, core",
    strain: "Elbows",
    desc: "Rowing up to the bar while holding a tuck front lever position.",
    steps: ["Hold a tuck front lever.", "Pull the bar toward the stomach, keeping the body horizontal.", "Lower back to straight arms.", "Keep the hips level throughout."],
    good: ["Body stays horizontal", "Full straight-arm bottom", "Retracted shoulders"],
    bad: ["Hips swinging up and down", "Half reps", "Kipping"],
    main: ["Tuck front lever rows"],
    acc: ["Inverted rows", "Tuck FL holds"],
    yt: [["Tuck front lever rows"]],
  }),
  S("pikefl", "Pike FL", C, "C", {
    pre: ["tuckfl"],
    hold: true,
    ttl: "1–3 months",
    muscles: "Lats, core, hamstring flexibility",
    strain: "Elbows",
    desc: "A front lever with straight legs piked toward the bar — an optional transition between tuck and straddle in the WINGS front lever guide.",
    steps: ["From a tuck front lever, extend the legs upward in a pike.", "Keep the back horizontal.", "Arms straight, shoulders retracted.", "Hold."],
    good: ["Straight legs", "Back level", "Straight arms"],
    bad: ["Hips dropping", "Bent knees", "Bent arms"],
    main: ["Pike front lever holds"],
    acc: ["Hamstring stretching", "Tuck FL"],
    yt: [["Pike front lever"]],
  }),
  S("pikeflrow", "Pike FL Row", C, "B", {
    pre: ["pikefl", "tuckflrow"],
    ttl: "2–4 months",
    muscles: "Lats, upper back, core",
    strain: "Elbows",
    desc: "Rows performed in a pike front lever.",
    steps: ["Hold a pike front lever.", "Row the bar toward the hips.", "Lower to straight arms.", "Keep the body level."],
    good: ["Level body", "Full range", "Steady tempo"],
    bad: ["Swinging", "Legs dropping", "Short reps"],
    main: ["Pike FL rows"],
    acc: ["Tuck FL rows"],
    yt: [["Pike front lever rows"]],
  }),
  S("advtuckfl", "Adv. Tuck FL", C, "C", {
    pre: ["tuckfl"],
    hold: true,
    ttl: "2–4 months",
    muscles: "Lats, core",
    strain: "Elbows, shoulders",
    desc: "Front lever stage II: a tuck with a flat back and open hips. Goal 15+ seconds.",
    steps: ["From a tuck front lever, flatten the back.", "Open the hips so the thighs are ~90° to the body.", "Keep the hips level with the shoulders.", "Hold with straight arms."],
    good: ["Flat back", "Hips at shoulder height", "Arms locked"],
    bad: ["Rounded back", "Hips dropping", "Bent arms"],
    main: ["Adv. tuck front lever holds"],
    acc: ["Dragon flags", "Hollow body hold"],
    yt: [["Advanced tuck front lever tutorial"]],
  }),
  S("superadvtuckfl", "Super Adv. Tuck FL", C, "B", {
    pre: ["advtuckfl"],
    hold: true,
    ttl: "3–6 months",
    muscles: "Lats, core, glutes",
    strain: "Elbows, shoulders",
    desc: "An advanced tuck with the hips opened further and an open pelvis (flat lower back) — WINGS stresses learning this pelvis position before straddle.",
    steps: ["Practise the open-pelvis position lying on your back (hollow).", "From an advanced tuck, push the knees further away.", "Keep the lower back flat.", "Hold."],
    good: ["Open pelvis", "Body level", "Retracted shoulders"],
    bad: ["Arched lower back", "Hips sinking", "Bent arms"],
    main: ["Super adv. tuck FL holds"],
    acc: ["Hollow body hold", "Dragon flags"],
    yt: [["Super advanced tuck front lever"]],
  }),
  S("advtuckflrow", "Adv. Tuck FL Row", C, "B", {
    pre: ["advtuckfl", "tuckflrow"],
    ttl: "2–4 months",
    muscles: "Lats, upper back, core",
    strain: "Elbows",
    desc: "Rows in an advanced tuck front lever — added in WINGS' stage II.",
    steps: ["Hold an advanced tuck FL.", "Row to the bar keeping the back flat.", "Lower with control.", "Repeat without the hips dropping."],
    good: ["Flat back", "Full range", "Level hips"],
    bad: ["Rounding into a tuck", "Swinging", "Partial reps"],
    main: ["Adv. tuck FL rows"],
    acc: ["Tuck FL rows", "Weighted pull-ups"],
    yt: [["Advanced tuck front lever rows"]],
  }),
  S("straddlefl", "Straddle FL", C, "B", {
    pre: ["superadvtuckfl", "pikefl"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Lats, core, glutes",
    strain: "Elbows, shoulders",
    desc: "Front lever stage III — the most time-consuming. Both legs straight and wide. Train holds, negatives and raises; bands (heavy to light, placed near the wrists) help bridge gaps.",
    steps: ["From a super adv. tuck, extend both legs wide.", "Keep the body horizontal and glutes engaged.", "Retract hard and press the bar down with straight arms.", "Hold, or do negatives and raises."],
    good: ["Legs straight and wide", "Horizontal body", "Locked arms"],
    bad: ["Piked hips", "Bent knees", "Hips below the shoulders"],
    main: ["Straddle FL holds", "Negatives / raises", "Banded straddle"],
    acc: ["Dragon flags", "Weighted pull-ups"],
    yt: [["Straddle front lever tutorial"]],
  }),
  S("straddleflrow", "Straddle FL Row", C, "A", {
    pre: ["straddlefl", "advtuckflrow"],
    ttl: "6–12 months",
    muscles: "Lats, upper back, core",
    strain: "Elbows, shoulders",
    desc: "Rows in a straddle front lever.",
    steps: ["Hold a straddle FL.", "Row the bar to the hips.", "Lower to straight arms.", "Keep the legs level."],
    good: ["Legs level", "Full range", "Controlled"],
    bad: ["Legs dropping", "Swinging", "Half reps"],
    main: ["Straddle FL rows"],
    acc: ["Adv. tuck FL rows"],
    yt: [["Straddle front lever rows"]],
  }),
  S("halflayfl", "Half Lay FL", C, "A", {
    pre: ["straddlefl"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Lats, core, glutes",
    strain: "Elbows, shoulders",
    desc: "The closest progression to the full front lever: legs together with the knees bent.",
    steps: ["From a straddle FL, bring the legs together.", "Bend the knees to shorten the lever.", "Keep the body level and pelvis open.", "Hold."],
    good: ["Body level", "Legs together", "Locked arms"],
    bad: ["Hips sagging", "Arching", "Bent arms"],
    main: ["Half lay FL holds"],
    acc: ["Straddle FL", "Banded full FL"],
    yt: [["Half lay front lever"]],
  }),
  S("fullfl", "Full Front Lever", C, "A", {
    pre: ["halflayfl"],
    hold: true,
    ttl: "1–2 years with daily training",
    muscles: "Lats, core, whole body",
    strain: "Elbows, shoulders",
    desc: "The whole body held straight and horizontal, face up, from straight arms. WINGS rates it A — about 1–2 years. Get there with holds, negatives and momentum raises.",
    steps: ["Build through straddle and half lay.", "Keep a slight hollow, legs together, everything squeezed.", "Retract and press the bar toward the hips.", "Hold."],
    good: ["Legs together", "Body horizontal and straight", "Locked arms"],
    bad: ["Arching", "Piking", "Bent arms"],
    main: ["Full FL holds", "Negatives", "Raises"],
    acc: ["Straddle FL", "Front lever rows"],
    yt: [["Full front lever tutorial progression"]],
  }),
  S("fullflrow", "Full FL Row", C, "S", {
    pre: ["fullfl", "straddleflrow"],
    ttl: "1+ year",
    muscles: "Lats, upper back, core",
    strain: "Elbows, shoulders",
    desc: "Rows in a full front lever.",
    steps: ["Hold a full front lever.", "Row the bar toward the hips.", "Lower with control.", "Body stays straight and level."],
    good: ["Straight body", "Full range", "Controlled"],
    bad: ["Hips dropping", "Arching", "Momentum"],
    main: ["Full FL rows"],
    acc: ["Straddle FL rows"],
    yt: [["Front lever rows full"]],
  }),
  S("fltouch", "Front Lever Touch", C, "S", {
    pre: ["fullflrow"],
    ttl: "1+ year",
    muscles: "Lats, upper back, core",
    strain: "Elbows, shoulders",
    desc: "From a full front lever, row until the bar touches your hips/stomach — an advanced option after the full lever.",
    steps: ["Hold a full front lever.", "Row explosively toward the bar.", "Touch the bar to the hips.", "Lower back to the lever."],
    good: ["Body stays horizontal", "Bar reaches the hips", "Controlled lowering"],
    bad: ["Piking to reach", "Kipping", "Short reps"],
    main: ["FL touch reps"],
    acc: ["Full FL rows", "Weighted pull-ups"],
    yt: [["Front lever touch tutorial"]],
  }),
];
