// Horizontal push — body roughly parallel to the ground (push-ups → planche).
import { S } from "./def.js";

const C = "hpush";
export default [
  S("assistedpu", "Assisted Push-up", C, "F", {
    ttl: "~1 week",
    muscles: "Chest, triceps, core",
    strain: "Wrists",
    desc: "A regression of the push-up. Any help counts — knees on the floor, hands on a bench (incline), or a band. It builds the strength for your first full push-up.",
    steps: ["Pick your version: knees on the floor, or hands on a bench or table.", "Hands shoulder-width, fingers forward or slightly out.", "Lower as one straight line until the chest is just above the floor or bench.", "Press back up. Lower the incline over the weeks until you reach the floor."],
    good: ["Elbows fairly close to the body", "Chest touches the floor / bench", "Body aligned through head, shoulders and hips", "Elbows ~90° at the bottom", "Hands shoulder-width, facing forward or slightly out"],
    bad: ["Flared elbows", "Sagging hips", "Weak / arched core", "High hips"],
    main: ["Knee push-ups", "Incline push-ups"],
    acc: ["Hollow body hold", "Sit-ups", "Wall push-ups"],
    yt: [["Can't do a push-up? Start push-ups from zero", "Can't Do A Push-Up How To Start Push-Ups From ZERO Fit Father Project"], ["Incline and knee push-up progression"]],
  }),
  S("pushup", "Push-up", C, "E", {
    pre: ["assistedpu"],
    ttl: "2–4 weeks",
    muscles: "Chest, triceps, front shoulders, core",
    strain: "Wrists, shoulders",
    desc: "The base of every pushing skill — a moving plank. WINGS' foundation goal is 20 clean reps; 15 comfortable reps is the signal to start pike push-ups, planche leans and pseudo push-ups.",
    steps: ["High plank, hands under the shoulders.", "Squeeze glutes and brace the stomach.", "Lower until the chest touches the floor, elbows ~45° from the body.", "Push the floor away to straight arms, shoulder blades spreading at the top."],
    good: ["Straight line head to heels", "Chest reaches the floor", "Elbows tucked about 45°", "Full lockout at the top"],
    bad: ["Hips sagging or piking", "Head poking forward", "Elbows flared to 90°", "Partial range"],
    main: ["Push-ups (aim for 20)", "Wide / close / diamond variations"],
    acc: ["Hollow body hold", "Planche lean"],
    yt: [["Perfect push-up form tutorial"], ["How to increase push-up reps"]],
  }),
  S("dip", "Dip", C, "D", {
    pre: ["pushup"],
    ttl: "2–4 weeks",
    muscles: "Chest, triceps, front shoulders",
    strain: "Shoulders, sternum",
    desc: "Lowering and pressing your whole body between parallel bars. A foundation exercise — WINGS' beginner goal is 15 reps — and a key strength builder for planche and muscle-up work.",
    steps: ["Support on the bars, arms straight, shoulders pushed down.", "Lean slightly forward and lower until the shoulders are just below the elbows.", "Keep the elbows tracking back, not out.", "Press back to full lockout."],
    good: ["Shoulders down, away from the ears", "Full depth (about 90° elbows)", "Controlled tempo"],
    bad: ["Shrugging", "Swinging the legs", "Bouncing out of the bottom"],
    main: ["Parallel bar dips (aim for 15)", "Dip negatives"],
    acc: ["Support hold", "Bench dips", "Push-ups"],
    yt: [["Perfect dip tutorial parallel bars"]],
  }),
  S("elbowlever", "Elbow Lever", C, "D", {
    pre: ["pushup"],
    hold: true,
    ttl: "2–4 weeks",
    muscles: "Core, wrists, shoulders",
    strain: "Wrists, elbows",
    desc: "Balancing horizontally with your hips resting on your bent elbows. Mostly balance — a fun first taste of planche-type positions and good wrist conditioning.",
    steps: ["Squat, hands on the floor, fingers turned slightly out or back.", "Bend the elbows and set them into your hips / lower stomach.", "Lean forward until the body tips onto the elbows.", "Straighten the legs behind you and hold, body level."],
    good: ["Elbows pressed into the hip bones", "Body straight and level", "Calm breathing"],
    bad: ["Elbows sliding apart", "Head dropping to the floor", "Bent, dangling legs"],
    main: ["Elbow lever holds", "One-leg elbow lever"],
    acc: ["Wrist conditioning", "Crow pose"],
    yt: [["Elbow lever tutorial"]],
  }),
  S("plean", "Planche Lean", C, "D", {
    pre: ["pushup"],
    hold: true,
    ttl: "2–4 weeks",
    muscles: "Front shoulders, serratus, core",
    strain: "Wrists",
    desc: "A straight-arm hold in push-up position with the shoulders leaned past the hands. The more you lean, the closer you move toward the planche — WINGS' leverage idea in its purest form.",
    steps: ["Push-up position, fingers turned out.", "Push the floor away (protract) and lock the elbows.", "Lean forward until the shoulders pass the wrists.", "Hold and breathe; lean further as you get stronger."],
    good: ["Arms locked", "Shoulders protracted and depressed", "Hollow, tight body"],
    bad: ["Bent elbows", "Shoulder blades pinched together", "Arched lower back"],
    main: ["Planche lean holds"],
    acc: ["Pseudo push-ups", "Hollow body hold"],
    yt: [["Planche lean tutorial beginner"]],
  }),
  S("pplpu", "Pseudo Push-up", C, "D", {
    pre: ["pushup"],
    ttl: "1–2 months",
    muscles: "Front shoulders, chest, triceps",
    strain: "Wrists, biceps tendon",
    desc: "A push-up with the hands down by the waist and the shoulders leaned well past them (pseudo planche push-up). Moving the hands toward your centre of mass makes every rep heavier — progressive overload by leverage.",
    steps: ["Hands by the lower ribs or waist, fingers out or back.", "Lean the shoulders forward over the hands and keep that lean.", "Lower with elbows close to the body.", "Push back up without losing the lean."],
    good: ["Shoulders stay ahead of the hands", "Protracted at the top", "Body straight"],
    bad: ["Leaning back during the rep", "Hands too far forward", "Sagging hips"],
    main: ["Pseudo planche push-ups"],
    acc: ["Planche lean", "Wrist conditioning"],
    yt: [["Pseudo planche push up tutorial"]],
  }),
  S("tuckpl", "Tuck Planche", C, "C", {
    pre: ["plean", "pplpu"],
    hold: true,
    ttl: "2–4 months",
    muscles: "Front shoulders, serratus, core, wrists",
    strain: "Wrists, elbows",
    desc: "Balanced on straight arms with the knees tucked to the chest and the feet off the floor — the first true planche.",
    steps: ["Squat with hands on the floor or parallettes, fingers out.", "Lean forward and round the upper back.", "Lift the feet and pull the knees into the chest.", "Keep the hips at shoulder height and hold."],
    good: ["Arms locked", "Back rounded, shoulders protracted", "Hips level with shoulders"],
    bad: ["Bent arms", "Hips too low", "Looking forward and arching"],
    main: ["Tuck planche holds", "Frog stand"],
    acc: ["Planche leans", "Pseudo push-ups"],
    yt: [["Tuck planche tutorial"]],
  }),
  S("tuckplpu", "Tuck Planche Push-up", C, "B", {
    pre: ["tuckpl"],
    ttl: "2–4 months",
    muscles: "Front shoulders, chest, triceps",
    strain: "Wrists, elbows",
    desc: "Push-ups performed in a tuck planche — the feet never touch the floor.",
    steps: ["Hold a solid tuck planche.", "Bend the elbows and lower the chest while keeping the lean.", "Go as deep as you can control (aim for 90°).", "Press back to the tuck planche."],
    good: ["Feet stay off the floor", "Hips stay high", "Elbows close"],
    bad: ["Dropping the hips as you lower", "Losing the lean", "Tiny range"],
    main: ["Tuck planche push-ups", "Negatives from tuck planche"],
    acc: ["Pseudo push-ups", "Dips"],
    yt: [["Tuck planche push up tutorial"]],
  }),
  S("ninetyhold", "90 Degree Hold", C, "B", {
    pre: ["elbowlever", "pplpu"],
    hold: true,
    ttl: "2–4 months",
    muscles: "Front shoulders, triceps, core",
    strain: "Wrists, elbows",
    desc: "A bent-arm planche: the body horizontal with the elbows bent at 90°. The bottom position of a 90° push-up.",
    steps: ["Start from an elbow lever or a pseudo push-up bottom.", "Lift the elbows away from the hips so only the hands support you.", "Keep the elbows at 90° and the body flat.", "Hold, then lower the feet with control."],
    good: ["Elbows at 90°", "Body level", "Elbows not resting on the hips"],
    bad: ["Using the hips as a shelf", "Sagging hips", "Elbows flaring wide"],
    main: ["90° holds (tuck → straddle → full)"],
    acc: ["Elbow lever", "Pseudo push-ups"],
    yt: [["90 degree hold tutorial calisthenics"]],
  }),
  S("backlever", "Back Lever", C, "B", {
    pre: ["dip", "plean"],
    hold: true,
    ttl: "3–6 months",
    muscles: "Biceps, chest, shoulders, lower back",
    strain: "Biceps tendon, shoulders",
    desc: "Hanging face-down with the body horizontal, arms straight behind you. A straight-arm skill that needs good shoulder extension — build it slowly.",
    steps: ["From a hang, tuck and rotate backwards into a German hang (skin the cat).", "From there lift up into a tuck back lever.", "Extend gradually: advanced tuck → straddle → full.", "Hold with straight arms and a tight body."],
    good: ["Straight arms", "Body horizontal", "Glutes squeezed"],
    bad: ["Bent arms", "Piked hips", "Rushing the shoulder stretch"],
    main: ["Tuck / straddle back lever holds", "Skin the cats"],
    acc: ["German hang", "Dips"],
    yt: [["Back lever progression tutorial"]],
  }),
  S("advtuckpl", "Adv. Tuck Planche", C, "B", {
    pre: ["tuckpl"],
    hold: true,
    ttl: "3–6 months",
    muscles: "Front shoulders, serratus, core",
    strain: "Wrists, elbows",
    desc: "A tuck planche with a flat back and the hips opened, so the knees sit away from the chest. Much harder because the body is longer. A common 'hardest meaningful hold' to build around.",
    steps: ["Get into a tuck planche.", "Flatten the back by pushing the hips back and up.", "Open the hips so the knees move away from the chest.", "Hold with straight arms."],
    good: ["Flat back", "Hips at shoulder height", "Locked arms"],
    bad: ["Rounded back (that's a tuck)", "Hips dropping", "Bent elbows"],
    main: ["Advanced tuck planche holds"],
    acc: ["Planche leans", "Banded holds"],
    yt: [["Advanced tuck planche tutorial"]],
  }),
  S("advtuckplpu", "Adv. Tuck Planche Push-up", C, "A", {
    pre: ["advtuckpl", "tuckplpu"],
    ttl: "4–8 months",
    muscles: "Front shoulders, chest, triceps",
    strain: "Wrists, elbows",
    desc: "Push-ups in an advanced tuck planche — flat back throughout.",
    steps: ["Hold an advanced tuck planche.", "Lower with the elbows close, keeping the back flat.", "Go to about 90°.", "Press back without the hips dropping."],
    good: ["Flat back the whole rep", "Feet off the floor", "Controlled"],
    bad: ["Rounding into a tuck to cheat", "Short range", "Hips sinking"],
    main: ["Adv. tuck planche push-ups"],
    acc: ["Tuck planche push-ups", "Dips"],
    yt: [["Advanced tuck planche push up"]],
  }),
  S("superadvtuckpl", "Super Adv. Tuck Planche", C, "A", {
    pre: ["advtuckpl"],
    hold: true,
    ttl: "4–8 months",
    muscles: "Front shoulders, core, glutes",
    strain: "Wrists, elbows",
    desc: "An advanced tuck with the hips opened even further and the knees pushed back — the bridge between tuck and straddle.",
    steps: ["From an advanced tuck, push the knees further back.", "Keep the pelvis tucked (posterior tilt) and the back flat.", "Hold the lean with locked arms.", "Build seconds before moving to straddle."],
    good: ["Open hips, flat back", "Posterior pelvic tilt", "Locked arms"],
    bad: ["Arching the lower back", "Hips dropping", "Bent arms"],
    main: ["Super adv. tuck planche holds"],
    acc: ["Banded straddle planche", "Planche leans"],
    yt: [["Super advanced tuck planche"]],
  }),
  S("straddlepl", "Straddle Planche", C, "A", {
    pre: ["superadvtuckpl"],
    hold: true,
    ttl: "1–2 years",
    muscles: "Front shoulders, core, glutes",
    strain: "Wrists, elbows, shoulders",
    desc: "A planche with straight legs spread wide. The wide legs shorten the lever compared with the full planche.",
    steps: ["From a super adv. tuck, extend the legs out to the sides.", "Keep the body flat and parallel to the floor.", "Squeeze glutes, point toes, tilt the pelvis under.", "Hold with locked arms."],
    good: ["Legs straight and wide", "Body parallel to the floor", "Arms locked"],
    bad: ["Piked hips", "Bent knees", "Not leaning enough"],
    main: ["Straddle planche holds", "Banded straddle"],
    acc: ["HSPU", "Back extensions", "Hollow holds"],
    yt: [["Straddle planche tutorial"]],
  }),
  S("straddleplpu", "Straddle Planche Push-up", C, "S", {
    pre: ["straddlepl", "advtuckplpu"],
    ttl: "1+ year",
    muscles: "Front shoulders, chest, triceps, core",
    strain: "Wrists, elbows, shoulders",
    desc: "Push-ups while holding a straddle planche.",
    steps: ["Hold a straddle planche.", "Lower with control, legs staying up.", "Touch near the floor or parallettes.", "Press back to the straddle."],
    good: ["Legs stay level", "Full range", "Smooth tempo"],
    bad: ["Legs dropping on the way down", "Short reps", "Piking"],
    main: ["Straddle planche push-ups"],
    acc: ["Adv. tuck planche push-ups", "Straddle holds"],
    yt: [["Straddle planche push up"]],
  }),
  S("halflaypl", "Half Lay Planche", C, "S", {
    pre: ["straddlepl"],
    hold: true,
    ttl: "1–2 years",
    muscles: "Front shoulders, core, glutes",
    strain: "Wrists, elbows, shoulders",
    desc: "A planche with the legs straight and together but bent at the knees (or straddled only slightly) — the step between straddle and full.",
    steps: ["From a straddle planche, bring the legs closer together.", "Bend the knees slightly to shorten the lever if needed.", "Keep the hips in line with the shoulders.", "Hold."],
    good: ["Body level", "Pelvis tucked", "Locked arms"],
    bad: ["Arching", "Hips sagging", "Bent arms"],
    main: ["Half lay planche holds"],
    acc: ["Straddle planche", "Banded full planche"],
    yt: [["Half lay planche tutorial"]],
  }),
  S("fullpl", "Full Planche", C, "S", {
    pre: ["halflaypl"],
    hold: true,
    ttl: "2+ years",
    muscles: "Front shoulders, core, whole body",
    strain: "Wrists, elbows, shoulders",
    desc: "The whole body horizontal on straight arms with the legs together. One of the hardest static holds in calisthenics — the end of WINGS' push roadmap.",
    steps: ["Build from straddle → half lay over months.", "Keep a slight hollow and lock the legs together.", "Lean far enough that the body balances over the hands.", "Hold."],
    good: ["Legs together", "Body straight and parallel", "Locked arms"],
    bad: ["Arching", "Piked hips", "Bent arms"],
    main: ["Full planche holds", "Negatives / raises"],
    acc: ["Straddle planche", "Planche push-ups"],
    yt: [["Full planche tutorial progression"]],
  }),
  S("fullplpu", "Full Planche Push-up", C, "S", {
    pre: ["fullpl", "straddleplpu"],
    ttl: "2+ years",
    muscles: "Front shoulders, chest, triceps, core",
    strain: "Wrists, elbows, shoulders",
    desc: "Push-ups in a full planche — elite pressing strength.",
    steps: ["Hold a full planche.", "Lower while keeping the body flat.", "Go as deep as you control.", "Press back to the planche."],
    good: ["Body flat throughout", "Legs together", "Controlled"],
    bad: ["Hips leading the movement", "Arching", "Short reps"],
    main: ["Full planche push-ups"],
    acc: ["Straddle planche push-ups"],
    yt: [["Full planche push up"]],
  }),
  S("oapl", "One Arm Planche", C, "S", {
    pre: ["fullpl"],
    hold: true,
    ttl: "Years",
    muscles: "Shoulders, core, obliques",
    strain: "Wrist, elbow, shoulder",
    desc: "A planche on one arm, usually in a straddle with the body slightly turned. Extremely rare.",
    steps: ["Master a strong full / straddle planche.", "Shift weight gradually onto one hand.", "Widen the legs and rotate slightly for balance.", "Lift the free hand."],
    good: ["Locked working arm", "Level body", "Controlled weight shift"],
    bad: ["Bent arm", "Twisting hard to compensate", "Skipping prerequisites"],
    main: ["Weight-shift planche holds"],
    acc: ["Full planche", "One-arm handstand"],
    yt: [["One arm planche"]],
  }),
  S("maltese", "Maltese", C, "S", {
    pre: ["fullpl"],
    hold: true,
    ttl: "Years",
    muscles: "Chest, front shoulders, biceps, core",
    strain: "Biceps tendon, shoulders, wrists",
    desc: "A planche with the hands placed very wide, so the body sits close to the floor. A peak gymnastics strength hold.",
    steps: ["Build a strong full planche first.", "Practise wide-hand planche leans.", "Widen the hands gradually.", "Hold with locked arms, body low and flat."],
    good: ["Locked arms", "Flat, low body", "Gradual hand widening"],
    bad: ["Bent arms", "Rushing hand width", "Ignoring biceps tendon soreness"],
    main: ["Wide planche leans", "Maltese holds"],
    acc: ["Full planche", "Straight-arm conditioning"],
    yt: [["Maltese planche calisthenics"]],
  }),
];
