// Legs — squats and their variations, plus hamstring / quad curls.
import { S } from "./def.js";

const C = "legs";
export default [
  S("squat", "Bodyweight Squat", C, "F", {
    ttl: "a few days",
    muscles: "Quads, glutes",
    strain: "Knees",
    desc: "Sitting down and standing up with only your bodyweight. WINGS' foundation goal is 20 reps.",
    steps: ["Feet shoulder-width, toes slightly out.", "Sit back and down, knees following the toes.", "Go to at least parallel.", "Stand tall, squeezing the glutes."],
    good: ["Heels stay down", "Knees track over toes", "Chest up"],
    bad: ["Knees caving in", "Heels lifting", "Half depth"],
    main: ["Bodyweight squats (aim for 20)"],
    acc: ["Glute bridges", "Wall sits"],
    yt: [["Bodyweight squat proper form"]],
  }),
  S("splitsquat", "Split Squat", C, "E", {
    pre: ["squat"],
    ttl: "1–2 weeks",
    muscles: "Quads, glutes",
    strain: "Knees",
    desc: "A static lunge — one foot forward, one back, lowering straight down.",
    steps: ["Step one foot forward into a long stance.", "Lower the back knee toward the floor.", "Front shin roughly vertical.", "Drive up through the front foot."],
    good: ["Torso upright", "Front heel down", "Back knee near the floor"],
    bad: ["Front knee caving", "Leaning forward a lot", "Short range"],
    main: ["Split squats"],
    acc: ["Squats", "Calf raises"],
    yt: [["Split squat form tutorial"]],
  }),
  S("bss", "Bulgarian Split Squat", C, "D", {
    pre: ["splitsquat"],
    ttl: "2–4 weeks",
    muscles: "Quads, glutes",
    strain: "Knees, hip flexors",
    desc: "A split squat with the back foot raised on a bench — much more load on the front leg.",
    steps: ["Back foot laces-down on a bench.", "Front foot far enough forward to sink straight down.", "Lower until the back knee nearly touches.", "Drive up through the front heel."],
    good: ["Balanced and upright", "Front knee tracks over toes", "Full depth"],
    bad: ["Front foot too close", "Bouncing", "Knee caving"],
    main: ["Bulgarian split squats"],
    acc: ["Split squats", "Glute bridges"],
    yt: [["Bulgarian split squat tutorial"]],
  }),
  S("assistedpistol", "Assisted Pistol Squat", C, "C", {
    pre: ["bss"],
    ttl: "1–2 months",
    muscles: "Quads, glutes, balance",
    strain: "Knees",
    desc: "A one-leg squat holding a pole or doorframe, or sitting to a box.",
    steps: ["Stand on one leg, the other straight in front.", "Hold a support lightly.", "Squat as deep as you can on one leg.", "Stand up using the support as little as possible."],
    good: ["Heel down", "Knee over toes", "Deep and controlled"],
    bad: ["Pulling up with the arms", "Heel lifting", "Collapsing at the bottom"],
    main: ["Assisted pistols", "Box pistols"],
    acc: ["Bulgarian split squats", "Ankle mobility"],
    yt: [["Assisted pistol squat progression"]],
  }),
  S("pistol", "Pistol Squat", C, "B", {
    pre: ["assistedpistol"],
    ttl: "2–4 months",
    muscles: "Quads, glutes, core",
    strain: "Knees, ankles",
    desc: "A full one-leg squat with the other leg held straight out in front.",
    steps: ["Stand on one leg, free leg straight forward, arms out.", "Sit down on one leg to full depth.", "Keep the free leg off the floor.", "Stand back up without help."],
    good: ["Full depth", "Heel down", "Free leg kept up"],
    bad: ["Knee caving", "Collapsing", "Bouncing"],
    main: ["Pistol squats"],
    acc: ["Assisted pistols", "L-sit (free leg strength)"],
    yt: [["Pistol squat tutorial"]],
  }),
  S("dragonpistol", "Dragon Pistol Squat", C, "S", {
    pre: ["pistol"],
    ttl: "6–12 months",
    muscles: "Quads, glutes, hip mobility, balance",
    strain: "Knees, hips",
    desc: "A pistol squat with the free leg wrapped behind the standing leg — needs great balance and hip mobility.",
    steps: ["Stand on one leg.", "Swing the free leg behind and across the standing leg.", "Squat down to full depth, free leg passing behind.", "Stand back up."],
    good: ["Controlled descent", "Standing heel down", "Upright torso"],
    bad: ["Forcing hip range", "Knee caving", "Falling into the bottom"],
    main: ["Dragon pistol attempts (assisted first)"],
    acc: ["Pistol squats", "Hip mobility"],
    yt: [["Dragon pistol squat tutorial"]],
  }),
  S("shrimp", "Shrimp Squat", C, "B", {
    pre: ["bss"],
    ttl: "2–4 months",
    muscles: "Quads, glutes",
    strain: "Knees",
    desc: "A one-leg squat holding the back foot behind you, touching the back knee to the floor.",
    steps: ["Stand on one leg, hold the other foot behind you.", "Lower until the back knee touches the floor.", "Lean forward slightly for balance.", "Stand back up."],
    good: ["Back knee touches lightly", "Controlled", "Standing knee tracks well"],
    bad: ["Crashing the knee down", "Knee caving", "Rushing"],
    main: ["Shrimp squats"],
    acc: ["Bulgarian split squats"],
    yt: [["Shrimp squat tutorial"]],
  }),
  S("sissy", "Sissy Squat", C, "C", {
    pre: ["splitsquat"],
    ttl: "1–2 months",
    muscles: "Quads",
    strain: "Knees",
    desc: "Leaning back while the knees travel far forward, heels up. Hits the quads very hard.",
    steps: ["Hold a support, rise onto the toes.", "Push the knees forward while leaning the torso back.", "Keep hips and torso in line.", "Lower as far as comfortable, then return."],
    good: ["Straight line knees to shoulders", "Controlled", "Use a support at first"],
    bad: ["Bending at the hips", "Dropping fast", "Forcing painful range"],
    main: ["Assisted sissy squats"],
    acc: ["Split squats", "Reverse Nordic curl"],
    yt: [["Sissy squat tutorial"]],
  }),
  S("reversenordic", "Reverse Nordic Curl", C, "C", {
    pre: ["squat"],
    ttl: "1–2 months",
    muscles: "Quads, hip flexors",
    strain: "Knees",
    desc: "Kneeling upright and leaning the whole body back as one straight line, then returning — quads only.",
    steps: ["Kneel on a pad, body upright.", "Lean back keeping a straight line knees to head.", "Go as far as you control.", "Pull back up with the quads."],
    good: ["Hips stay extended", "Slow and controlled", "Padding under the knees"],
    bad: ["Bending at the hips", "Dropping fast", "Arching"],
    main: ["Reverse Nordic curls"],
    acc: ["Sissy squats", "Split squats"],
    yt: [["Reverse nordic curl tutorial"]],
  }),
  S("nordic", "Nordic Curl", C, "A", {
    pre: ["splitsquat"],
    ttl: "6–12 months",
    muscles: "Hamstrings",
    strain: "Hamstrings, knees",
    desc: "Kneeling with the ankles anchored, lowering forward and pulling back up with the hamstrings alone. Start with slow negatives.",
    steps: ["Kneel on a pad, ankles anchored.", "Keep a straight line knees to head.", "Lower forward as slowly as you can (negatives first).", "Pull back up with the hamstrings without pushing off."],
    good: ["Hips extended throughout", "Very slow descent", "Hands ready to catch"],
    bad: ["Hip hinge to cheat", "Dropping fast", "No padding"],
    main: ["Nordic negatives", "Nordic curls"],
    acc: ["Glute bridges", "Romanian deadlifts"],
    yt: [["Nordic hamstring curl progression"]],
  }),
];
