// Vertical pull — body perpendicular to the ground (hangs → pull-ups → muscle-up / one-arm pull-up).
import { S } from "./def.js";

const C = "vpull";
export default [
  S("deadhang", "Deadhang", C, "F", {
    hold: true,
    ttl: "a few days",
    muscles: "Grip, forearms, lats (stretch)",
    strain: "Shoulders, hands",
    desc: "Hanging from a bar with straight arms and relaxed shoulders. Builds grip and gets the shoulders used to hanging.",
    steps: ["Grab a bar slightly wider than shoulders.", "Lift the feet and hang with straight arms.", "Relax into the stretch but keep a firm grip.", "Hold, breathing slowly."],
    good: ["Full grip, thumbs around the bar", "Arms straight", "Steady breathing"],
    bad: ["Swinging", "Holding the breath", "Partial grip"],
    main: ["Dead hangs"],
    acc: ["Farmer's carries"],
    yt: [["Dead hang how to"]],
  }),
  S("activehang", "Active Hang", C, "F", {
    pre: ["deadhang"],
    hold: true,
    ttl: "~1 week",
    muscles: "Lats, lower traps, grip",
    strain: "Shoulders",
    desc: "A hang with the shoulders pulled down and back (engaged) instead of relaxed — the starting position of every good pull-up.",
    steps: ["From a dead hang, pull the shoulders away from the ears.", "Keep the arms straight.", "Squeeze slightly back as well (retraction).", "Hold the engaged position."],
    good: ["Arms straight", "Shoulders down", "Body still"],
    bad: ["Bending the elbows", "Shrugging up", "Swinging"],
    main: ["Active hang holds"],
    acc: ["Dead hang", "Scapula pull-ups"],
    yt: [["Active hang vs dead hang"]],
  }),
  S("scappull", "Scapula Pull-up", C, "F", {
    pre: ["activehang"],
    ttl: "~1 week",
    muscles: "Lower traps, lats",
    strain: "Shoulders",
    desc: "Moving between dead hang and active hang for reps, arms straight. Teaches the first part of every pull-up; a front lever supplement too.",
    steps: ["Dead hang.", "Pull the shoulder blades down and back — the body rises a few cm.", "Pause, then relax back down.", "Arms stay straight."],
    good: ["Arms straight", "Shoulders move away from the ears", "Slow tempo"],
    bad: ["Bending the elbows", "Swinging", "Shrugging"],
    main: ["Scapula pull-ups"],
    acc: ["Active hang", "Inverted rows"],
    yt: [["Scapula pull up tutorial"]],
  }),
  S("assistedpullup", "Assisted Pull-up", C, "E", {
    pre: ["scappull"],
    ttl: "2–4 weeks",
    muscles: "Lats, biceps, upper back",
    strain: "Elbows",
    desc: "A full-range pull-up with help — a band, machine, partner or feet on a box. Negatives (slow lowering) count too.",
    steps: ["Loop a band over the bar and put a foot or knee in it.", "Start from a dead hang.", "Pull until the chin clears the bar.", "Lower fully. Use lighter bands over time."],
    good: ["Full range", "Shoulders engaged first", "Controlled lowering"],
    bad: ["Half reps", "Relying fully on the band", "Shrugging"],
    main: ["Band-assisted pull-ups", "Pull-up negatives"],
    acc: ["Inverted rows", "Scapula pull-ups"],
    yt: [["Band assisted pull up tutorial"]],
  }),
  S("pullup", "Pull-up", C, "D", {
    pre: ["assistedpullup"],
    ttl: "1–3 months",
    muscles: "Lats, biceps, upper back, core",
    strain: "Elbows, shoulders",
    desc: "Chin over the bar from a dead hang, palms away. WINGS' foundation goal is 10 reps; 10–15 is the front lever prerequisite. Try wide and close grips too.",
    steps: ["Dead hang, hands just wider than shoulders.", "Engage the shoulders, then drive the elbows down.", "Chin clears the bar, chest toward it.", "Lower to fully straight arms."],
    good: ["From dead hang", "Chin over bar", "No swing"],
    bad: ["Kipping", "Half reps", "Reaching with the chin"],
    main: ["Pull-ups (aim for 10)", "Wide / close grip"],
    acc: ["Inverted rows", "Hollow body hold"],
    yt: [["Perfect pull up form tutorial"]],
  }),
  S("chestpullup", "Chest Pull-up", C, "C", {
    pre: ["pullup"],
    ttl: "1–2 months",
    muscles: "Lats, upper back, biceps",
    strain: "Elbows, shoulders",
    desc: "Pulling explosively until the chest touches the bar. WINGS' beginner phase ends with chest and waist pulls — explosive pulling is the focus.",
    steps: ["Dead hang with a tight body.", "Pull hard and fast.", "Bring the chest to the bar, leaning back slightly.", "Lower with control."],
    good: ["Explosive pull", "Chest touches the bar", "Tight body"],
    bad: ["Big kip", "Slow reps", "Chin-only reps"],
    main: ["Chest-to-bar pull-ups"],
    acc: ["Pull-ups", "Inverted rows"],
    yt: [["Chest to bar pull up strict"]],
  }),
  S("waistpullup", "Waist Pull-up", C, "B", {
    pre: ["chestpullup"],
    ttl: "2–4 months",
    muscles: "Lats, upper back, triceps",
    strain: "Elbows, shoulders",
    desc: "An even higher explosive pull — the bar reaches your waist. Makes muscle-ups (and clean ones) much easier.",
    steps: ["Dead hang, hollow body.", "Pull as explosively as possible, slightly away from the bar.", "Push the bar down past the chest toward the waist.", "Control the descent."],
    good: ["Maximum height", "Bar to waist", "Strict hollow body"],
    bad: ["Kipping", "Pulling straight into the bar", "Sloppy landing"],
    main: ["Waist-height pull-ups"],
    acc: ["Chest pull-ups", "Straight bar dips"],
    yt: [["High pull ups waist to bar"]],
  }),
  S("muscleup", "Muscle-Up", C, "B", {
    pre: ["chestpullup"],
    ttl: "2–6 months",
    muscles: "Lats, chest, triceps, shoulders",
    strain: "Elbows, wrists, shoulders",
    desc: "A pull-up that flows over the bar into a dip. Path 1 of WINGS' intermediate pull phase: muscle-up → archer pull-up → one-arm pull-up.",
    steps: ["Use a slightly false / high grip.", "Pull explosively toward the hips, slightly away from the bar.", "As the bar reaches the chest, lean over and drive the elbows up (the transition).", "Press out of the dip to lockout."],
    good: ["Explosive pull", "Fast elbow turnover", "Lockout on top"],
    bad: ["Chicken-winging one arm over", "Too much kip", "Pulling straight up into the bar"],
    main: ["Muscle-ups", "Band-assisted muscle-ups"],
    acc: ["Chest pull-ups", "Straight bar dips"],
    yt: [["Muscle up tutorial step by step"]],
  }),
  S("cleanmu", "Clean Muscle-Up", C, "A", {
    pre: ["muscleup", "waistpullup"],
    ttl: "4–8 months",
    muscles: "Lats, chest, triceps, core",
    strain: "Elbows, shoulders",
    desc: "A strict muscle-up with no kip or swing — straight body, smooth transition.",
    steps: ["Dead hang, hollow body, no swing.", "Pull to the waist strictly.", "Turn the wrists and elbows over quickly.", "Press to lockout, legs still together."],
    good: ["No leg kick", "Smooth transition", "Both arms together"],
    bad: ["Kipping", "One arm at a time", "Swinging"],
    main: ["Strict muscle-ups", "Slow muscle-ups"],
    acc: ["Waist pull-ups", "Straight bar dips"],
    yt: [["Strict muscle up tutorial no kip"]],
  }),
  S("archerpullup", "Archer Pull-up", C, "B", {
    pre: ["pullup"],
    ttl: "2–4 months",
    muscles: "Lats, biceps (one side)",
    strain: "Elbows",
    desc: "A wide pull-up toward one hand while the other arm straightens. The linear path to the one-arm pull-up.",
    steps: ["Take a very wide grip.", "Pull toward one hand as the other arm straightens.", "Lower and switch sides.", "Slide the assisting hand further out over time."],
    good: ["Assisting arm straight", "Chin over the working hand", "Controlled"],
    bad: ["Bending both arms equally", "Swinging", "Partial range"],
    main: ["Archer pull-ups", "Typewriter pull-ups"],
    acc: ["Weighted pull-ups", "One-arm hangs"],
    yt: [["Archer pull up tutorial"]],
  }),
  S("assistedoac", "Assisted OAC", C, "A", {
    pre: ["archerpullup"],
    ttl: "4–8 months",
    muscles: "Lats, biceps, forearms",
    strain: "Elbows",
    desc: "One-arm chin-up (palm facing you) with help — the free hand holding a towel, band or the wrist of the working arm lower down.",
    steps: ["Grip the bar with one hand, palm facing you.", "Hold a towel or band with the other hand, lower down.", "Pull mainly with the bar arm.", "Use less help over time."],
    good: ["Working arm does most of the work", "Engaged shoulder", "Full range"],
    bad: ["Pulling evenly with both", "Passive shoulder", "Kipping"],
    main: ["Towel-assisted one-arm chin-ups"],
    acc: ["Archer pull-ups", "One-arm negatives"],
    yt: [["Assisted one arm chin up"]],
  }),
  S("assistedoap", "Assisted OAP", C, "A", {
    pre: ["archerpullup"],
    ttl: "4–8 months",
    muscles: "Lats, biceps, forearms",
    strain: "Elbows",
    desc: "One-arm pull-up (palm facing away) with help from the other hand on a towel or band.",
    steps: ["Grip the bar with one hand, palm away.", "Assist with the other hand on a towel / band.", "Pull, keeping the body from twisting too much.", "Reduce assistance gradually."],
    good: ["Engaged shoulder", "Controlled rotation", "Full range"],
    bad: ["Even pulling", "Dropping into the bottom", "Kipping"],
    main: ["Towel-assisted one-arm pull-ups"],
    acc: ["Archer pull-ups", "Weighted pull-ups"],
    yt: [["Assisted one arm pull up"]],
  }),
  S("oapullup", "OAC / OAP", C, "S", {
    pre: ["assistedoac", "assistedoap"],
    ttl: "1–2+ years",
    muscles: "Lats, biceps, forearms, core",
    strain: "Elbows, shoulders",
    desc: "A full one-arm chin-up (OAC) or one-arm pull-up (OAP) — one of the rarest strength skills.",
    steps: ["Hang on one arm, shoulder engaged.", "Pull with the body slightly turned toward the working arm.", "Chin over the bar.", "Lower with control."],
    good: ["Engaged shoulder from the start", "Minimal rotation", "Full range"],
    bad: ["Hanging passively", "Big kip", "Uncontrolled drop"],
    main: ["One-arm pull-ups / chin-ups", "One-arm negatives"],
    acc: ["Assisted OAC / OAP", "Weighted pull-ups"],
    yt: [["One arm pull up tutorial progression"]],
  }),
  S("weightedpu", "Weighted Pull-ups", C, "C", {
    pre: ["pullup"],
    ttl: "Ongoing",
    muscles: "Lats, biceps, upper back",
    strain: "Elbows",
    desc: "Pull-ups with added weight (belt, backpack or vest). WINGS calls them a bonus that speeds up both the front lever and one-arm pull-up — log the weight in a note.",
    steps: ["Add a small weight (2.5–5 kg) with a belt or backpack.", "Do strict pull-ups with full range.", "Work in the 4–8 rep range for strength.", "Add weight when all sets feel solid."],
    good: ["Strict form", "Full range", "Gradual loading"],
    bad: ["Kipping with weight", "Jumping in big steps", "Half reps"],
    main: ["Weighted pull-ups 3–5 × 4–8"],
    acc: ["Pull-ups", "Inverted rows"],
    yt: [["Weighted pull ups for calisthenics"]],
  }),
  S("butterfly", "Butterfly", C, "C", {
    pre: ["chestpullup"],
    ttl: "1–2 months",
    muscles: "Lats, core, hip flexors, shoulders",
    strain: "Shoulders, hands",
    desc: "The butterfly pull-up: a fast, continuous kipping pull-up where the body moves in a smooth loop. It's about rhythm and coordination rather than strict strength — build strict pull-ups first.",
    steps: ["Learn a strong kip swing (hollow ↔ arch).", "Pull as the hips drive up in the hollow.", "Push away at the top and flow straight into the next swing.", "Keep a steady rhythm."],
    good: ["Smooth, continuous loop", "Shoulders engaged", "Strict base strength first"],
    bad: ["Learning it before strict pull-ups", "Choppy rhythm", "Relaxed shoulders at the bottom"],
    main: ["Kip swings", "Butterfly pull-ups"],
    acc: ["Chest pull-ups", "Hollow body hold"],
    yt: [["Butterfly pull up tutorial"]],
  }),
];
