// Vertical push — body perpendicular to the ground (pike push-ups → handstands → HSPU).
import { S } from "./def.js";

const C = "vpush";
export default [
  S("pikepu", "Pike Push-up", C, "E", {
    ttl: "2–4 weeks",
    muscles: "Shoulders, triceps, upper chest",
    strain: "Wrists, shoulders",
    desc: "Hips high in an upside-down V, head lowered toward the floor. Your first overhead press with bodyweight — step 1 of the WINGS handstand path.",
    steps: ["From a push-up, walk the feet in and lift the hips high.", "Hands shoulder-width, eyes toward the feet.", "Lower the head to a spot in front of the hands (a triangle).", "Press back up; hips stay high."],
    good: ["Hips high", "Head lands in front of the hands", "Elbows not fully flared"],
    bad: ["Turning it into a push-up", "Head straight down between the hands", "Short range"],
    main: ["Pike push-ups", "Elevated pike hold"],
    acc: ["Diamond push-ups", "Wrist conditioning"],
    yt: [["Pike push up tutorial"]],
  }),
  S("crow", "Crow Pose", C, "E", {
    hold: true,
    ttl: "1–2 weeks",
    muscles: "Wrists, shoulders, core",
    strain: "Wrists",
    desc: "Knees resting on the backs of the arms while you balance on your hands. Teaches balance on the hands — a first step to handstands and planche.",
    steps: ["Squat, hands shoulder-width, fingers spread.", "Bend the elbows slightly and rest the knees on the upper arms.", "Lean forward until the feet float.", "Look slightly forward and hold."],
    good: ["Fingers spread and gripping", "Weight on the hands", "Calm breathing"],
    bad: ["Looking straight down", "Not leaning enough", "Collapsed shoulders"],
    main: ["Crow pose holds"],
    acc: ["Wrist conditioning", "Planche lean"],
    yt: [["Crow pose tutorial beginners"]],
  }),
  S("wallhs", "Assisted Handstand", C, "D", {
    pre: ["pikepu"],
    hold: true,
    ttl: "2–4 weeks",
    muscles: "Shoulders, triceps, core",
    strain: "Wrists, shoulders",
    desc: "A handstand against the wall. WINGS' order: back-to-wall first to get used to being upside down (aim for 30 s), then chest-to-wall for a straight line and heel-of-palm control.",
    steps: ["Back-to-wall: kick up with hands about a foot from the wall and hold 30 s.", "Learn the bail-out: move one hand forward, twist toward it and step down.", "Chest-to-wall: walk the feet up the wall, hands close to it.", "Push tall, squeeze glutes, point toes, look between the hands."],
    good: ["Arms straight by the ears", "Stacked: wrists–shoulders–hips–feet", "Pushing tall (elevation)", "Breathing"],
    bad: ["Banana back", "Bent elbows", "Shoulders not fully overhead"],
    main: ["Back-to-wall holds", "Chest-to-wall holds"],
    acc: ["Pike push-ups", "Hollow body hold", "Wrist warm-up"],
    yt: [["Chest to wall handstand tutorial"], ["How to bail out of a handstand"]],
  }),
  S("hs", "Handstand", C, "C", {
    pre: ["wallhs", "crow"],
    hold: true,
    ttl: "2–3 months with daily practice",
    muscles: "Shoulders, wrists, core",
    strain: "Wrists",
    desc: "Balancing on your hands without support. WINGS rates it C — about 2–3 months of daily practice. Balance comes from the fingers (stop falling over) and the heel of the palm (stop falling back).",
    steps: ["Warm up wrists, shoulders and a hollow body.", "Practise balance near the wall (hands < 1 ft away), touching it less and less.", "Kick up freestanding from a lunge, hands a foot in front.", "Stack, push tall, correct with fingers and palm. Bail out by twisting."],
    good: ["Straight arms and legs", "Stacked line", "Look between the hands", "Pointed toes"],
    bad: ["Over-arched back", "Bent arms", "Fear of bailing"],
    main: ["Freestanding kick-ups", "Wall-assisted balance"],
    acc: ["Crow pose", "Wrist conditioning"],
    yt: [["Freestanding handstand tutorial beginners"]],
  }),
  S("elevpike", "Elevated Pike Push-up", C, "D", {
    pre: ["pikepu"],
    ttl: "1–2 months",
    muscles: "Shoulders, triceps",
    strain: "Wrists, shoulders",
    desc: "Pike push-ups with the feet on a box, so more weight is over the hands. A core HSPU builder in the push roadmap.",
    steps: ["Feet on a box, hands on the floor, hips stacked over the shoulders.", "Lower the head in front of the hands.", "Press to straight arms.", "Raise the box over time."],
    good: ["Hips over shoulders", "Full range", "Steady core"],
    bad: ["Hips drifting back", "Short reps", "Flared elbows"],
    main: ["Elevated pike push-ups", "Elevated pike holds"],
    acc: ["Pike push-ups", "Assisted handstand"],
    yt: [["Elevated pike push up tutorial"]],
  }),
  S("bentarmstand", "Bent Arm Stand", C, "C", {
    pre: ["crow", "wallhs"],
    hold: true,
    ttl: "1–2 months",
    muscles: "Shoulders, triceps, core",
    strain: "Wrists, elbows",
    desc: "A handstand balanced on bent arms (like the bottom of a handstand push-up without the head down). Recommended alongside HSPU training.",
    steps: ["From crow or a wall, bring the hips over the hands with elbows bent.", "Lift the legs up into a tuck, then straight.", "Keep elbows over the wrists.", "Hold the balance."],
    good: ["Elbows over wrists", "Hips stacked", "Fingers active"],
    bad: ["Elbows flaring", "Hips drifting forward", "Holding the breath"],
    main: ["Bent arm stand holds"],
    acc: ["Crow pose", "Pike push-ups"],
    yt: [["Bent arm stand tutorial"]],
  }),
  S("bentarmpress", "Bent Arm Press to HS", C, "B", {
    pre: ["hs", "bentarmstand"],
    ttl: "2–4 months",
    muscles: "Shoulders, core, hip flexors",
    strain: "Wrists, shoulders",
    desc: "Pressing from a bent-arm position (like crow) up into a handstand without kicking.",
    steps: ["Start in crow or a bent arm stand.", "Shift the shoulders forward and lift the hips over the hands.", "Bring the legs up through tuck to straight.", "Straighten the arms into a handstand."],
    good: ["No jump or kick", "Hips lead the movement", "Controlled finish"],
    bad: ["Kicking up", "Overbalancing", "Rushing"],
    main: ["Crow to handstand", "Press negatives"],
    acc: ["Handstand", "L-sit compression"],
    yt: [["Crow to handstand press tutorial"]],
  }),
  S("straightarmpress", "Straight Arm Press to HS", C, "A", {
    pre: ["bentarmpress"],
    ttl: "6–12 months",
    muscles: "Shoulders, core, compression, hamstring flexibility",
    strain: "Wrists, shoulders, hamstrings",
    desc: "Pressing to handstand with straight arms (straddle or pike). Needs strong compression and flexibility as well as balance.",
    steps: ["Stand in a wide straddle, hands on the floor in front.", "Lean the shoulders forward over the hands.", "Lift the hips high and float the feet up.", "Bring the legs together into a handstand."],
    good: ["Arms stay locked", "Shoulders lean forward", "Slow and controlled"],
    bad: ["Jumping", "Bent arms", "Not enough lean"],
    main: ["Press negatives", "Elevated press practice"],
    acc: ["L-sit compression", "Pancake stretch"],
    yt: [["Straddle press to handstand tutorial"]],
  }),
  S("wallhspu", "Assisted HSPU", C, "C", {
    pre: ["elevpike", "wallhs"],
    ttl: "1–3 months",
    muscles: "Shoulders, triceps, upper back",
    strain: "Neck, shoulders, wrists",
    desc: "Handstand push-ups using the wall (chest-to-wall is WINGS' pick). The main intermediate goal in the push roadmap — HSPU strength carries over to the planche.",
    steps: ["Kick up chest-to-wall (or back-to-wall).", "Lower slowly until the head touches a soft pad.", "Head and hands form a triangle.", "Press back to lockout. Use negatives if you can't press yet."],
    good: ["Controlled descent", "Triangle position", "Full lockout"],
    bad: ["Dropping onto the head", "Kipping", "Elbows flared wide"],
    main: ["Wall HSPU", "HSPU negatives"],
    acc: ["Elevated pike push-ups", "Bent arm stand"],
    yt: [["Chest to wall handstand push up tutorial"]],
  }),
  S("hspu", "HSPU", C, "B", {
    pre: ["wallhspu", "hs"],
    ttl: "3–6 months",
    muscles: "Shoulders, triceps, core",
    strain: "Wrists, shoulders",
    desc: "A freestanding handstand push-up. WINGS' intermediate target is 3–5 clean reps.",
    steps: ["Hold a steady freestanding handstand.", "Lower with a slight lean, keeping the balance.", "Touch the head lightly.", "Press back to a balanced handstand."],
    good: ["Balance through the rep", "Control at the bottom", "Full lockout"],
    bad: ["Falling over at the bottom", "Big arch", "Rushing"],
    main: ["HSPU (aim for 3–5)", "Freestanding negatives"],
    acc: ["Assisted HSPU", "Handstand holds"],
    yt: [["Freestanding handstand push up tutorial"]],
  }),
  S("deephspu", "Deep HSPU", C, "A", {
    pre: ["hspu"],
    ttl: "6–12 months",
    muscles: "Shoulders, triceps, upper back",
    strain: "Shoulders, wrists",
    desc: "HSPU on parallettes or blocks so the head goes below the hands — a much longer range.",
    steps: ["Set up on parallettes or blocks.", "Lower until the shoulders reach the hands.", "Keep the elbows tracking forward.", "Press all the way up."],
    good: ["Full depth", "Controlled", "Stacked at the top"],
    bad: ["Bouncing", "Elbows flaring", "Losing the line"],
    main: ["Deficit HSPU (wall first)"],
    acc: ["HSPU", "Dips"],
    yt: [["Deficit handstand push up"]],
  }),
  S("ninetypu", "90 Degree Push-up", C, "S", {
    pre: ["deephspu"],
    ttl: "1–2 years",
    muscles: "Shoulders, triceps, core",
    strain: "Wrists, elbows, shoulders",
    desc: "Lowering from a handstand into a 90° hold (body horizontal on bent arms) and pressing back up.",
    steps: ["Start in a handstand.", "Lower into the 90° position, body becoming horizontal.", "Hold the 90° briefly.", "Press back up to handstand."],
    good: ["Elbows at 90° at the bottom", "Smooth transition", "Tight body"],
    bad: ["Collapsing at the bottom", "Using momentum", "Skipping the 90 hold"],
    main: ["90° push-up negatives"],
    acc: ["90 degree hold", "Deep HSPU"],
    yt: [["90 degree push up tutorial"]],
  }),
  S("assistedoahs", "Assisted OAHS", C, "A", {
    pre: ["hs"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Shoulders, wrists, obliques",
    strain: "Wrist, shoulder",
    desc: "One-arm handstand practice with help — fingertips of the other hand on the floor, or against a wall.",
    steps: ["Hold a straddle handstand.", "Shift weight onto one arm.", "Lighten the other hand to fingertips.", "Lift it for short moments."],
    good: ["Stacked over the working arm", "Straddle for balance", "Patient weight shift"],
    bad: ["Bent working arm", "Big hip swings", "Rushing"],
    main: ["Fingertip-assisted OAHS", "Wall OAHS"],
    acc: ["Handstand", "Wrist conditioning"],
    yt: [["One arm handstand progression"]],
  }),
  S("oahs", "OAHS", C, "S", {
    pre: ["assistedoahs"],
    hold: true,
    ttl: "Years",
    muscles: "Shoulders, wrists, whole body",
    strain: "Wrist, shoulder",
    desc: "A freestanding one-arm handstand.",
    steps: ["Build long, stable straddle handstands.", "Shift fully over one arm.", "Lift the free hand and balance with the fingers.", "Hold."],
    good: ["Locked arm", "Quiet balance", "Straddle legs"],
    bad: ["Bent arm", "Over-correcting", "Fatigued practice"],
    main: ["One-arm handstand attempts"],
    acc: ["Assisted OAHS", "Handstand shapes"],
    yt: [["One arm handstand tutorial"]],
  }),
  S("oaflag", "OA Flag", C, "S", {
    pre: ["oahs"],
    hold: true,
    ttl: "Years",
    muscles: "Shoulders, obliques, whole body",
    strain: "Wrist, shoulder",
    desc: "A one-arm flag balanced on the floor — the body held out sideways from one straight arm.",
    steps: ["Master the one-arm handstand.", "From a one-arm straddle, lower the legs sideways.", "Keep the hips stacked over the hand.", "Hold."],
    good: ["Locked arm", "Hips stacked", "Body straight sideways"],
    bad: ["Bent arm", "Hips sagging", "Skipping prerequisites"],
    main: ["One-arm flag attempts"],
    acc: ["OAHS", "Human flag"],
    yt: [["One arm flag calisthenics"]],
  }),
];
