// Calisthenics skill tree, modelled on the WINGS skill tree (wingssw.com):
// six families, each a tree from easiest (bottom) to hardest (top).
// Status levels follow WINGS: locked → unlocked (1 rep / 2 s) → in progress
// (3 reps / 6 s) → mastered (6+ reps / 12+ s).
// Text is our own summary; videos are YouTube searches so links never go stale.

export const CATEGORIES = [
  { id: "hpush", label: "Horizontal push", short: "H. push" },
  { id: "vpush", label: "Vertical push", short: "V. push" },
  { id: "hpull", label: "Horizontal pull", short: "H. pull" },
  { id: "vpull", label: "Vertical pull", short: "V. pull" },
  { id: "core", label: "Core", short: "Core" },
  { id: "legs", label: "Legs", short: "Legs" },
];

export const DIFFICULTY = ["F", "E", "D", "C", "B", "A", "S"]; // easiest → hardest

export const LEVELS = [
  { id: "locked", label: "Locked", color: "#4b4b55", reps: 0, hold: 0 },
  { id: "unlocked", label: "Unlocked", color: "#f4f4f5", reps: 1, hold: 2 },
  { id: "progress", label: "In progress", color: "#c084b8", reps: 3, hold: 6 },
  { id: "mastered", label: "Mastered", color: "#c5d68f", reps: 6, hold: 12 },
];

const yt = (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

const S = (id, name, cat, diff, o) => ({
  id,
  name,
  cat,
  diff,
  pre: o.pre || [],
  hold: Boolean(o.hold),
  ttl: o.ttl,
  muscles: o.muscles,
  strain: o.strain || "—",
  desc: o.desc,
  steps: o.steps,
  good: o.good,
  bad: o.bad,
  main: o.main,
  acc: o.acc,
  videos: (o.yt || []).map(([title, q]) => ({ title, url: yt(q || title) })),
});

export const SKILLS = [
  /* ---------------- Horizontal push ---------------- */
  S("wallpu", "Wall Push-up", "hpush", "F", {
    ttl: "a few days",
    muscles: "Chest, triceps, front shoulders",
    strain: "Wrists",
    desc: "The gentlest push-up: hands on a wall, body leaning in. It teaches the push-up pattern — straight body, elbows tucked — with only a small part of your bodyweight.",
    steps: ["Stand an arm's length from a wall, hands on it at shoulder height and width.", "Lean in as one straight plank from head to heels.", "Bend the elbows until your chest nearly touches the wall.", "Push back to straight arms. Step further back to make it harder."],
    good: ["Body stays in one straight line", "Elbows about 45° from the body", "Full range — chest close to the wall"],
    bad: ["Bending at the hips", "Flared elbows", "Half reps"],
    main: ["Wall push-ups"],
    acc: ["Plank", "Scapula push-ups"],
    yt: [["Wall push-up tutorial for beginners"], ["How to do a proper push-up progression from the wall"]],
  }),
  S("assistedpu", "Assisted Push-up", "hpush", "F", {
    pre: ["wallpu"],
    ttl: "~1 week",
    muscles: "Chest, triceps, core",
    strain: "Wrists",
    desc: "A regression of the regular push-up. Any form of help counts — knees on the floor, hands on a bench (incline), or a band. It builds the strength to do your first full push-up.",
    steps: ["Pick your version: knees on the floor, or hands on a bench or table.", "Hands shoulder-width, fingers forward or slightly out.", "Lower as one straight line until the chest is just above the floor or bench.", "Press back up. Lower the incline over the weeks until you reach the floor."],
    good: ["Elbows relatively close to the body", "Chest touches the floor / bench", "Body aligned through head, shoulders, hips (and legs)", "Elbows at ~90° at the bottom", "Hands shoulder-width, facing forward or slightly out"],
    bad: ["Flared elbows", "Sagging hips", "Weak / arched core", "High hips"],
    main: ["Knee push-ups", "Incline push-ups"],
    acc: ["Hollow body hold", "Sit-ups", "Wall push-ups"],
    yt: [["Can't do a push-up? How to start push-ups from zero", "Can't Do A Push-Up How To Start Push-Ups From ZERO Fit Father Project"], ["Incline and knee push-up progression"]],
  }),
  S("pushup", "Push-up", "hpush", "E", {
    pre: ["assistedpu"],
    ttl: "2–4 weeks",
    muscles: "Chest, triceps, front shoulders, core",
    strain: "Wrists, shoulders",
    desc: "The base of every pushing skill. A moving plank: your whole body goes down and up together while the arms do the work.",
    steps: ["Start in a high plank, hands under the shoulders.", "Squeeze glutes and brace the stomach.", "Lower until the chest touches the floor, elbows ~45° from the body.", "Push the floor away until the arms are straight and the shoulder blades spread."],
    good: ["Straight line head to heels", "Chest reaches the floor", "Elbows tucked about 45°", "Full lockout at the top"],
    bad: ["Hips sagging or piking", "Head poking forward", "Elbows flared to 90°", "Partial range"],
    main: ["Push-ups", "Slow negatives"],
    acc: ["Plank", "Dips (bench)", "Hollow body hold"],
    yt: [["Perfect push-up form tutorial"], ["How to increase push-up reps progression"]],
  }),
  S("diamondpu", "Diamond Push-up", "hpush", "D", {
    pre: ["pushup"],
    ttl: "2–4 weeks",
    muscles: "Triceps, inner chest",
    strain: "Elbows, wrists",
    desc: "Hands together under the chest so the triceps do far more of the work. A strong bridge towards dips, handstand push-ups and planche work.",
    steps: ["From a push-up position, make a diamond with thumbs and index fingers under the sternum.", "Keep the body straight and elbows close to the ribs.", "Lower until the chest touches the hands.", "Press back up to lockout."],
    good: ["Elbows brush the sides", "Chest touches the hands", "Hips in line"],
    bad: ["Elbows flaring out wide", "Shortened range", "Hips piking up"],
    main: ["Diamond push-ups", "Close-grip push-ups"],
    acc: ["Bench dips", "Triceps extensions (bodyweight)"],
    yt: [["Diamond push-up tutorial form"]],
  }),
  S("archerpu", "Archer Push-up", "hpush", "C", {
    pre: ["pushup"],
    ttl: "1–2 months",
    muscles: "Chest, triceps, shoulders (one side at a time)",
    strain: "Shoulders, elbows",
    desc: "A wide push-up where you shift your weight over one arm while the other stays straight like a bow string. The main stepping stone to the one-arm push-up.",
    steps: ["Set the hands about twice shoulder-width apart.", "Lower towards one hand, bending that elbow while the other arm stays straight.", "Push back to the middle and switch sides.", "Use the straight arm less and less over time."],
    good: ["Working elbow tucked", "Assisting arm stays straight", "Hips square to the floor"],
    bad: ["Twisting the hips", "Bending the assisting arm", "Bouncing out of the bottom"],
    main: ["Archer push-ups", "Typewriter push-ups"],
    acc: ["Diamond push-ups", "Plank shoulder taps"],
    yt: [["Archer push-up tutorial progression"]],
  }),
  S("oapu", "One-arm Push-up", "hpush", "B", {
    pre: ["archerpu"],
    ttl: "3–6 months",
    muscles: "Chest, triceps, shoulders, obliques",
    strain: "Shoulders, wrists",
    desc: "A full push-up on one hand, feet wide for balance. It needs a lot of pressing strength plus anti-rotation core control.",
    steps: ["Feet wider than shoulders, one hand under the chest, the other behind the back.", "Brace hard — the body will want to twist.", "Lower with control until the chest is a fist from the floor.", "Press up without rotating. Start with incline one-arm push-ups."],
    good: ["Hips and shoulders stay level", "Working elbow tucked", "Controlled descent"],
    bad: ["Rotating the torso", "Feet too close together", "Dropping into the bottom"],
    main: ["Incline one-arm push-ups", "One-arm negatives"],
    acc: ["Archer push-ups", "Side plank"],
    yt: [["One arm push-up tutorial progression"]],
  }),
  S("pplpu", "Pseudo Planche Push-up", "hpush", "C", {
    pre: ["pushup"],
    ttl: "1–2 months",
    muscles: "Front shoulders, chest, biceps (straight-arm)",
    strain: "Wrists, biceps tendon",
    desc: "A push-up with the hands down by the waist, fingers turned out, and the shoulders leaning well past the hands. It trains the forward lean the planche needs.",
    steps: ["Place hands by the lower ribs or waist, fingers out or back.", "Lean the shoulders forward over the hands and hold that lean.", "Lower while keeping the lean, elbows close.", "Push back up without losing the forward position."],
    good: ["Shoulders stay ahead of the hands", "Scapula protracted (back rounded slightly) at the top", "Body straight"],
    bad: ["Leaning back during the rep", "Hands too far forward", "Sagging hips"],
    main: ["Pseudo planche push-ups"],
    acc: ["Planche lean", "Wrist conditioning"],
    yt: [["Pseudo planche push up tutorial"]],
  }),
  S("plean", "Planche Lean", "hpush", "D", {
    pre: ["pushup"],
    hold: true,
    ttl: "2–4 weeks",
    muscles: "Front shoulders, serratus, core",
    strain: "Wrists",
    desc: "A straight-arm hold in the push-up position with the shoulders leaned well past the hands. The first static step towards the planche.",
    steps: ["Start in a push-up position with fingers turned out.", "Push the floor away (protract) and lock the elbows.", "Lean forward until the shoulders are past the wrists.", "Hold, breathing, then lean further as you get stronger."],
    good: ["Arms locked straight", "Shoulders protracted", "Hollow, tight body"],
    bad: ["Bent elbows", "Shoulder blades pinched together", "Arched lower back"],
    main: ["Planche lean holds"],
    acc: ["Pseudo planche push-ups", "Hollow body hold"],
    yt: [["Planche lean tutorial beginner"]],
  }),
  S("tuckpl", "Tuck Planche", "hpush", "B", {
    pre: ["plean", "pplpu"],
    hold: true,
    ttl: "2–4 months",
    muscles: "Front shoulders, serratus, core, wrists",
    strain: "Wrists, elbows",
    desc: "The whole body balanced on straight arms with the knees tucked to the chest and the feet off the floor — the first true planche.",
    steps: ["Squat with hands on the floor or parallettes, fingers out.", "Lean forward and round the upper back.", "Lift the feet and pull the knees into the chest.", "Keep the hips at shoulder height and hold."],
    good: ["Arms straight", "Back rounded, shoulders protracted", "Hips level with shoulders"],
    bad: ["Bent arms", "Hips too low", "Looking forward and arching"],
    main: ["Tuck planche holds", "Frog stand"],
    acc: ["Planche leans", "Pseudo planche push-ups"],
    yt: [["Tuck planche tutorial"]],
  }),
  S("advtuckpl", "Advanced Tuck Planche", "hpush", "A", {
    pre: ["tuckpl"],
    hold: true,
    ttl: "3–6 months",
    muscles: "Front shoulders, serratus, core",
    strain: "Wrists, elbows",
    desc: "Like the tuck planche but with a flat back and hips opened so the knees sit away from the chest. Much harder because the body is longer.",
    steps: ["Get into a tuck planche.", "Flatten the back by pushing the hips back and up.", "Open the hip angle so the knees move away from the chest.", "Hold with straight arms."],
    good: ["Flat back", "Hips at shoulder height", "Straight, locked arms"],
    bad: ["Rounded back (that's a tuck)", "Hips dropping", "Bending elbows"],
    main: ["Advanced tuck planche holds"],
    acc: ["Planche leans", "Tuck planche push-ups"],
    yt: [["Advanced tuck planche tutorial"]],
  }),
  S("straddlepl", "Straddle Planche", "hpush", "S", {
    pre: ["advtuckpl"],
    hold: true,
    ttl: "1–2 years",
    muscles: "Front shoulders, core, glutes",
    strain: "Wrists, elbows, shoulders",
    desc: "A planche with straight legs spread wide. The wide legs shorten the lever compared with the full planche.",
    steps: ["From an advanced tuck, extend the legs out to the sides.", "Keep the body flat and parallel to the floor.", "Squeeze the glutes and point the toes.", "Hold with locked arms."],
    good: ["Legs straight and wide", "Body parallel to the floor", "Arms locked"],
    bad: ["Piked hips", "Bent knees", "Shoulders not leaned enough"],
    main: ["Straddle planche holds", "Half-lay planche"],
    acc: ["Advanced tuck planche", "Band-assisted planche"],
    yt: [["Straddle planche tutorial"]],
  }),
  S("fullpl", "Full Planche", "hpush", "S", {
    pre: ["straddlepl"],
    hold: true,
    ttl: "2+ years",
    muscles: "Front shoulders, core, whole body",
    strain: "Wrists, elbows, shoulders",
    desc: "The whole body held horizontal on straight arms with the legs together. One of the hardest static holds in calisthenics.",
    steps: ["Build from the straddle planche, narrowing the legs over months.", "Keep a slight hollow and lock the legs together.", "Lean far enough that the body balances over the hands.", "Hold."],
    good: ["Legs together", "Body straight and parallel", "Locked arms"],
    bad: ["Arching the back", "Piked hips", "Bent arms"],
    main: ["Full planche holds"],
    acc: ["Straddle planche", "Planche push-ups"],
    yt: [["Full planche tutorial progression"]],
  }),

  /* ---------------- Vertical push ---------------- */
  S("benchdip", "Bench Dip", "vpush", "F", {
    ttl: "~1 week",
    muscles: "Triceps, front shoulders",
    strain: "Shoulders",
    desc: "Hands on a bench behind you, feet on the floor. A gentle way to learn the dipping movement.",
    steps: ["Sit on a bench edge, hands beside the hips, fingers forward.", "Slide off so the hips are in front of the bench.", "Bend the elbows straight back to about 90°.", "Press back up. Straighten the legs to make it harder."],
    good: ["Elbows point back, not out", "Shoulders down away from ears", "Hips close to the bench"],
    bad: ["Going too deep and rolling the shoulders forward", "Elbows flaring", "Shrugging"],
    main: ["Bench dips"],
    acc: ["Diamond push-ups", "Support hold"],
    yt: [["Bench dip proper form"]],
  }),
  S("dip", "Parallel Bar Dip", "vpush", "E", {
    pre: ["benchdip"],
    ttl: "2–4 weeks",
    muscles: "Chest, triceps, front shoulders",
    strain: "Shoulders, sternum",
    desc: "Lowering and pressing your whole body between two bars. A foundation for straight-bar dips and the muscle-up.",
    steps: ["Start in a support hold, arms straight, shoulders down.", "Lean slightly forward and lower until the shoulders are just below the elbows.", "Keep elbows tracking back.", "Press to full lockout."],
    good: ["Shoulders depressed (away from ears)", "Full depth, about 90° elbows", "Controlled tempo"],
    bad: ["Shrugging", "Swinging the legs", "Bouncing at the bottom"],
    main: ["Parallel bar dips", "Dip negatives"],
    acc: ["Support hold", "Bench dips", "Push-ups"],
    yt: [["Perfect dip tutorial parallel bars"]],
  }),
  S("sbdip", "Straight Bar Dip", "vpush", "C", {
    pre: ["dip"],
    ttl: "1–2 months",
    muscles: "Triceps, chest, shoulders",
    strain: "Wrists, shoulders",
    desc: "A dip on a single bar with the bar in front of you — the second half of a muscle-up.",
    steps: ["Jump to support on a straight bar, bar at hip height.", "Lean the chest over the bar, legs slightly in front.", "Lower until the bar touches the chest/upper stomach.", "Press back to lockout."],
    good: ["Chest over the bar", "Elbows back", "Full range"],
    bad: ["Staying upright and falling back", "Partial reps", "Kipping"],
    main: ["Straight bar dips"],
    acc: ["Parallel bar dips", "Negative straight bar dips"],
    yt: [["Straight bar dip tutorial"]],
  }),
  S("ringdip", "Ring Dip", "vpush", "B", {
    pre: ["dip"],
    ttl: "2–3 months",
    muscles: "Chest, triceps, shoulders, stabilisers",
    strain: "Shoulders",
    desc: "Dips on gymnastic rings. The rings move, so every small stabiliser has to work.",
    steps: ["Master a steady ring support hold (rings turned out).", "Lower with the rings close to the body.", "Go down until the shoulders are below the elbows.", "Press up and turn the rings out at the top."],
    good: ["Rings close to the body", "Steady support at the top", "Turned-out rings at lockout"],
    bad: ["Rings drifting wide", "Shaking through a shortened range", "Shrugging"],
    main: ["Ring dips", "Ring support hold"],
    acc: ["Parallel bar dips", "Ring push-ups"],
    yt: [["Ring dip tutorial beginner"]],
  }),
  S("pikepu", "Pike Push-up", "vpush", "D", {
    pre: ["benchdip"],
    ttl: "2–4 weeks",
    muscles: "Shoulders, triceps, upper chest",
    strain: "Wrists, shoulders",
    desc: "Hips high in an upside-down V, head lowered towards the floor. Your first overhead press with bodyweight.",
    steps: ["From a push-up, walk the feet in and lift the hips high.", "Hands shoulder-width, head looking at the feet.", "Lower the head to a spot in front of the hands (a triangle).", "Press back up, hips stay high."],
    good: ["Hips high", "Head goes forward of the hands", "Elbows not flared fully out"],
    bad: ["Turning it into a push-up", "Head straight down between hands", "Short range"],
    main: ["Pike push-ups"],
    acc: ["Wall plank / chest-to-wall hold", "Diamond push-ups"],
    yt: [["Pike push up tutorial"]],
  }),
  S("elevpike", "Elevated Pike Push-up", "vpush", "C", {
    pre: ["pikepu"],
    ttl: "1–2 months",
    muscles: "Shoulders, triceps",
    strain: "Wrists, shoulders",
    desc: "Pike push-ups with the feet on a box or bench, so more of your weight is over the hands.",
    steps: ["Feet on a box, hands on the floor, hips stacked over the shoulders.", "Lower the head forward of the hands.", "Press up to straight arms.", "Raise the box height over time."],
    good: ["Hips over shoulders", "Full range", "Steady core"],
    bad: ["Hips drifting back", "Short reps", "Flared elbows"],
    main: ["Elevated pike push-ups"],
    acc: ["Pike push-ups", "Wall handstand"],
    yt: [["Elevated pike push up tutorial"]],
  }),
  S("crow", "Crow Pose", "vpush", "E", {
    hold: true,
    ttl: "1–2 weeks",
    muscles: "Wrists, shoulders, core",
    strain: "Wrists",
    desc: "Knees resting on the backs of the arms while you balance on your hands. It teaches balance on the hands — the first step to handstands.",
    steps: ["Squat, hands shoulder-width on the floor, fingers spread.", "Bend the elbows slightly and rest the knees on the upper arms.", "Lean forward until the feet float.", "Look slightly forward and hold."],
    good: ["Fingers spread and gripping", "Weight on the hands, not the head", "Calm breathing"],
    bad: ["Looking straight down", "Not leaning enough", "Collapsing the shoulders"],
    main: ["Crow pose holds", "Frog stand"],
    acc: ["Wrist conditioning", "Planche lean"],
    yt: [["Crow pose tutorial beginners"]],
  }),
  S("wallhs", "Wall Handstand", "vpush", "D", {
    pre: ["pikepu"],
    hold: true,
    ttl: "2–4 weeks",
    muscles: "Shoulders, triceps, core",
    strain: "Wrists, shoulders",
    desc: "A handstand with the wall for balance. Chest-to-wall is best for learning a straight line.",
    steps: ["Facing away from the wall, walk the feet up it while walking the hands in.", "Get the chest close to the wall (chest-to-wall).", "Push tall through the shoulders, squeeze the glutes, point the toes.", "Hold, then walk down with control."],
    good: ["Arms by the ears, shoulders open", "Straight line, ribs in", "Pushing tall"],
    bad: ["Banana back", "Bent elbows", "Shoulders closed (not overhead)"],
    main: ["Chest-to-wall handstand"],
    acc: ["Pike push-ups", "Hollow body hold"],
    yt: [["Chest to wall handstand tutorial"]],
  }),
  S("hs", "Freestanding Handstand", "vpush", "B", {
    pre: ["wallhs", "crow"],
    hold: true,
    ttl: "3–12 months",
    muscles: "Shoulders, wrists, core",
    strain: "Wrists",
    desc: "Balancing upside down on your hands without support. Balance comes from the fingers and wrists.",
    steps: ["Kick up with one leg from a lunge, hands about a foot in front.", "Stack hips over shoulders over hands.", "Fingers press to stop falling over; heel of the hand to stop under-balancing.", "Practise bail-outs (cartwheel out) so falling is safe."],
    good: ["Stacked line", "Active shoulders", "Corrections from the fingers"],
    bad: ["Over-arched back", "Bent arms", "Fear of bailing"],
    main: ["Handstand kick-ups", "Wall handstand toe pulls"],
    acc: ["Crow pose", "Wrist conditioning"],
    yt: [["Freestanding handstand tutorial beginners"], ["How to bail out of a handstand"]],
  }),
  S("wallhspu", "Wall Handstand Push-up", "vpush", "B", {
    pre: ["elevpike", "wallhs"],
    ttl: "2–6 months",
    muscles: "Shoulders, triceps, upper back",
    strain: "Neck, shoulders, wrists",
    desc: "A full-range overhead press in a wall handstand — bodyweight's version of the strict overhead press.",
    steps: ["Kick up to a wall handstand (back to the wall).", "Lower slowly until the head touches a soft pad.", "Head and hands form a triangle.", "Press back to lockout."],
    good: ["Controlled descent", "Triangle position at the bottom", "Full lockout"],
    bad: ["Dropping onto the head", "Kipping", "Elbows flaring wide"],
    main: ["Wall HSPU", "Wall HSPU negatives"],
    acc: ["Elevated pike push-ups", "Wall handstand holds"],
    yt: [["Handstand push up tutorial wall progression"]],
  }),
  S("hspu", "Freestanding Handstand Push-up", "vpush", "S", {
    pre: ["wallhspu", "hs"],
    ttl: "1+ year",
    muscles: "Shoulders, triceps, core",
    strain: "Wrists, shoulders",
    desc: "A handstand push-up without the wall — strength and balance together.",
    steps: ["Hold a steady freestanding handstand.", "Lower with a slight lean, keeping the balance.", "Touch the head lightly (or go deeper on parallettes).", "Press back to a balanced handstand."],
    good: ["Balance kept through the rep", "Control at the bottom", "Full lockout"],
    bad: ["Falling over at the bottom", "Big arch", "Rushing"],
    main: ["Freestanding HSPU negatives"],
    acc: ["Wall HSPU", "Handstand holds"],
    yt: [["Freestanding handstand push up tutorial"]],
  }),

  /* ---------------- Horizontal pull ---------------- */
  S("inclinerow", "Incline Row", "hpull", "F", {
    ttl: "~1 week",
    muscles: "Upper back, rear shoulders, biceps",
    strain: "Elbows",
    desc: "Pulling your chest to a high bar or table edge while leaning back at an angle — the start of all rowing.",
    steps: ["Hold a chest-height bar, walk the feet forward so the body leans back.", "Keep a straight line from head to heels.", "Pull the chest to the bar, squeezing the shoulder blades together.", "Lower with control. Walk the feet further forward to make it harder."],
    good: ["Body straight", "Chest to the bar", "Shoulder blades squeeze back"],
    bad: ["Hips sagging", "Pulling only with the arms", "Shrugging up"],
    main: ["Incline rows", "Table rows"],
    acc: ["Scapula retractions", "Dead hang"],
    yt: [["Incline row bodyweight beginner"]],
  }),
  S("austrow", "Australian Row", "hpull", "E", {
    pre: ["inclinerow"],
    ttl: "2–3 weeks",
    muscles: "Upper back, lats, biceps",
    strain: "Elbows",
    desc: "A bodyweight row under a waist-height bar with the body nearly horizontal.",
    steps: ["Hang under a waist-height bar, body straight, heels on the floor.", "Pull the chest to the bar.", "Pause and squeeze the back.", "Lower to straight arms."],
    good: ["Rigid plank body", "Chest touches the bar", "Full extension at the bottom"],
    bad: ["Piking at the hips", "Half reps", "Head reaching for the bar"],
    main: ["Australian rows", "Ring rows"],
    acc: ["Scapula pulls", "Face pulls (band)"],
    yt: [["Australian pull up row tutorial"]],
  }),
  S("archerrow", "Archer Row", "hpull", "C", {
    pre: ["austrow"],
    ttl: "1–2 months",
    muscles: "Upper back, lats, biceps (one side)",
    strain: "Elbows",
    desc: "A wide-grip row where one arm does the pulling and the other stays straight — towards the one-arm row.",
    steps: ["Take a wide grip under a bar or rings.", "Pull towards one hand, the other arm straight.", "Return and switch sides.", "Rely less on the straight arm over time."],
    good: ["Body doesn't twist", "Straight assisting arm", "Full range"],
    bad: ["Rotating hips", "Bending the assisting arm", "Rushing"],
    main: ["Archer rows"],
    acc: ["Australian rows", "Side plank"],
    yt: [["Archer row tutorial calisthenics"]],
  }),
  S("skinthecat", "Skin the Cat", "hpull", "D", {
    pre: ["inclinerow"],
    ttl: "2–6 weeks",
    muscles: "Shoulders (mobility), lats, core",
    strain: "Shoulders",
    desc: "Rotating backwards through the arms on a bar or rings into a German hang and back. Builds shoulder mobility and the tuck position for levers.",
    steps: ["Hang from rings or a bar.", "Tuck the knees and roll backwards between the arms.", "Lower into a German hang only as far as is comfortable.", "Reverse back to a hang with control."],
    good: ["Slow and controlled", "Straight arms", "Comfortable depth"],
    bad: ["Dropping into the bottom", "Bent arms", "Forcing range"],
    main: ["Skin the cats", "German hang"],
    acc: ["Tuck front lever", "Hanging knee raises"],
    yt: [["Skin the cat tutorial rings"]],
  }),
  S("tuckfl", "Tuck Front Lever", "hpull", "C", {
    pre: ["austrow"],
    hold: true,
    ttl: "1–2 months",
    muscles: "Lats, core, rear shoulders",
    strain: "Elbows, shoulders",
    desc: "Hanging face-up with the back horizontal and knees tucked, arms straight. The first step to the front lever.",
    steps: ["Hang from a bar, pull the shoulders down.", "Tuck the knees and rotate back until the back is flat and horizontal.", "Press the bar down towards the hips with straight arms.", "Hold."],
    good: ["Straight arms", "Back parallel to the floor", "Shoulders depressed"],
    bad: ["Hips too low", "Bent elbows", "Shrugged shoulders"],
    main: ["Tuck front lever holds", "Tuck front lever raises"],
    acc: ["Hanging leg raises", "Australian rows"],
    yt: [["Tuck front lever tutorial"]],
  }),
  S("advtuckfl", "Advanced Tuck Front Lever", "hpull", "B", {
    pre: ["tuckfl"],
    hold: true,
    ttl: "2–4 months",
    muscles: "Lats, core",
    strain: "Elbows, shoulders",
    desc: "A tuck front lever with a flat back and open hips, so the knees are away from the chest.",
    steps: ["From a tuck front lever, flatten the back.", "Open the hips so the thighs are about 90° to the body.", "Keep the hips level with the shoulders.", "Hold with straight arms."],
    good: ["Flat back", "Hips at shoulder height", "Arms locked"],
    bad: ["Rounded back", "Hips dropping", "Bent arms"],
    main: ["Advanced tuck front lever holds"],
    acc: ["Front lever raises", "Hollow body hold"],
    yt: [["Advanced tuck front lever tutorial"]],
  }),
  S("onelegfl", "One-leg Front Lever", "hpull", "A", {
    pre: ["advtuckfl"],
    hold: true,
    ttl: "3–6 months",
    muscles: "Lats, core, hip flexors",
    strain: "Elbows",
    desc: "A front lever with one leg straight and one tucked — a half-way step to full.",
    steps: ["From an advanced tuck, extend one leg fully.", "Keep the body horizontal.", "Alternate legs each set.", "Hold."],
    good: ["Horizontal body", "Extended leg straight", "Straight arms"],
    bad: ["Extended leg dropping", "Hips sagging", "Arching"],
    main: ["One-leg front lever holds"],
    acc: ["Advanced tuck front lever", "Front lever negatives"],
    yt: [["One leg front lever tutorial"]],
  }),
  S("straddlefl", "Straddle Front Lever", "hpull", "A", {
    pre: ["onelegfl"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Lats, core, glutes",
    strain: "Elbows, shoulders",
    desc: "A front lever with both legs straight and spread wide.",
    steps: ["From one-leg front lever, extend both legs wide apart.", "Keep the body horizontal and the glutes engaged.", "Press the bar down with straight arms.", "Hold."],
    good: ["Legs straight and wide", "Body horizontal", "Locked arms"],
    bad: ["Piked hips", "Bent knees", "Hips below shoulders"],
    main: ["Straddle front lever holds"],
    acc: ["One-leg front lever", "Front lever raises"],
    yt: [["Straddle front lever tutorial"]],
  }),
  S("fullfl", "Full Front Lever", "hpull", "S", {
    pre: ["straddlefl"],
    hold: true,
    ttl: "1–2 years",
    muscles: "Lats, core, whole body",
    strain: "Elbows, shoulders",
    desc: "The whole body held straight and horizontal, face-up, hanging from straight arms.",
    steps: ["Narrow the straddle over time until the legs are together.", "Keep a slight hollow and squeeze everything.", "Press the bar down towards the hips.", "Hold."],
    good: ["Legs together", "Body horizontal and straight", "Arms locked"],
    bad: ["Arching", "Piking", "Bent arms"],
    main: ["Full front lever holds"],
    acc: ["Straddle front lever", "Front lever rows"],
    yt: [["Full front lever tutorial progression"]],
  }),

  /* ---------------- Vertical pull ---------------- */
  S("deadhang", "Dead Hang", "vpull", "F", {
    hold: true,
    ttl: "a few days",
    muscles: "Grip, forearms, lats (stretch)",
    strain: "Shoulders, hands",
    desc: "Simply hanging from a bar with straight arms. Builds grip and gets the shoulders used to hanging.",
    steps: ["Grab a bar slightly wider than shoulders.", "Lift the feet and hang with straight arms.", "Relax into the stretch but keep a firm grip.", "Hold, breathing slowly."],
    good: ["Full grip, thumbs around the bar", "Arms straight", "Steady breathing"],
    bad: ["Swinging", "Holding the breath", "Partial grip"],
    main: ["Dead hangs"],
    acc: ["Farmer's carries", "Scapula pulls"],
    yt: [["Dead hang benefits how to"]],
  }),
  S("scappull", "Scapula Pull-up", "vpull", "F", {
    pre: ["deadhang"],
    ttl: "~1 week",
    muscles: "Lower traps, lats",
    strain: "Shoulders",
    desc: "From a dead hang, pull the shoulders down without bending the arms. Teaches the first part of every pull-up.",
    steps: ["Hang with straight arms.", "Pull the shoulder blades down and slightly back — the body rises a few cm.", "Pause, then relax back to the hang.", "Arms stay straight throughout."],
    good: ["Arms straight", "Shoulders move down, away from ears", "Slow tempo"],
    bad: ["Bending the elbows", "Swinging", "Shrugging up"],
    main: ["Scapula pull-ups"],
    acc: ["Dead hang", "Incline rows"],
    yt: [["Scapula pull up tutorial"]],
  }),
  S("negpu", "Negative Pull-up", "vpull", "E", {
    pre: ["scappull"],
    ttl: "1–3 weeks",
    muscles: "Lats, biceps, upper back",
    strain: "Elbows",
    desc: "Jump or step to the top of a pull-up and lower yourself as slowly as you can.",
    steps: ["Use a box to get your chin over the bar.", "Hold the top briefly.", "Lower slowly (aim for 3–5 seconds) to straight arms.", "Step back up and repeat."],
    good: ["Slow, even descent", "Full extension at the bottom", "Chest up"],
    bad: ["Dropping quickly", "Stopping half way", "Kicking"],
    main: ["Pull-up negatives"],
    acc: ["Scapula pull-ups", "Australian rows"],
    yt: [["Negative pull ups tutorial"]],
  }),
  S("assistedpullup", "Assisted Pull-up", "vpull", "E", {
    pre: ["scappull"],
    ttl: "2–4 weeks",
    muscles: "Lats, biceps, upper back",
    strain: "Elbows",
    desc: "A pull-up with help — a band, a machine, a partner or your feet on a box — through the full range.",
    steps: ["Loop a band over the bar and put a foot or knee in it (or use the machine).", "Start from a dead hang.", "Pull until the chin clears the bar.", "Lower fully. Use lighter bands over time."],
    good: ["Full range", "Shoulders down at the start", "Controlled lowering"],
    bad: ["Half reps", "Relying fully on the band", "Shrugging"],
    main: ["Band-assisted pull-ups", "Assisted pull-up machine"],
    acc: ["Negative pull-ups", "Incline rows"],
    yt: [["Band assisted pull up tutorial"]],
  }),
  S("pullup", "Pull-up", "vpull", "D", {
    pre: ["negpu", "assistedpullup"],
    ttl: "1–3 months",
    muscles: "Lats, biceps, upper back, core",
    strain: "Elbows, shoulders",
    desc: "Pulling your chin over the bar from a dead hang, palms facing away. The king of upper-body pulling.",
    steps: ["Dead hang, hands just wider than shoulders, palms away.", "Pull the shoulders down first, then drive the elbows down.", "Chin clears the bar, chest towards the bar.", "Lower to fully straight arms."],
    good: ["From dead hang", "Chin over bar", "No swing"],
    bad: ["Kipping", "Half reps", "Chin poking forward to 'reach'"],
    main: ["Pull-ups", "Negatives"],
    acc: ["Australian rows", "Hollow body hold"],
    yt: [["Perfect pull up form tutorial"], ["How to get your first pull up"]],
  }),
  S("chinup", "Chin-up", "vpull", "D", {
    pre: ["assistedpullup"],
    ttl: "1–2 months",
    muscles: "Biceps, lats",
    strain: "Elbows",
    desc: "A pull-up with palms facing you. Usually a little easier thanks to the biceps.",
    steps: ["Shoulder-width grip, palms towards you.", "Pull the chest towards the bar.", "Chin over the bar.", "Lower to straight arms."],
    good: ["Full range", "Elbows drive down", "No swing"],
    bad: ["Half reps", "Kicking", "Shrugging"],
    main: ["Chin-ups"],
    acc: ["Biceps curls (bodyweight)", "Negatives"],
    yt: [["Chin up tutorial form"]],
  }),
  S("lsitpu", "L-sit Pull-up", "vpull", "C", {
    pre: ["pullup"],
    ttl: "1–2 months",
    muscles: "Lats, biceps, core, hip flexors",
    strain: "Elbows",
    desc: "A strict pull-up while holding the legs straight out in an L. Removes any swing.",
    steps: ["Hang and lift the straight legs to horizontal.", "Hold the L while pulling the chin over the bar.", "Lower with the legs still up.", "Bend the knees (tuck) if needed."],
    good: ["Legs stay horizontal", "Strict, no swing", "Full range"],
    bad: ["Legs dropping during the pull", "Bent knees creeping in", "Half reps"],
    main: ["L-sit pull-ups", "Tuck pull-ups"],
    acc: ["Hanging leg raises", "L-sit"],
    yt: [["L sit pull up tutorial"]],
  }),
  S("explosivepu", "Explosive Pull-up", "vpull", "C", {
    pre: ["pullup"],
    ttl: "1–2 months",
    muscles: "Lats, upper back, biceps",
    strain: "Elbows, shoulders",
    desc: "Pull-ups as high and fast as possible — chest or even waist to the bar. Needed for the muscle-up.",
    steps: ["Start from a dead hang with tight body.", "Pull as hard and fast as you can.", "Aim to get the chest to the bar.", "Lower with control between reps."],
    good: ["Maximum speed", "Chest to bar", "Body stays tight"],
    bad: ["Big kip", "Slow reps", "Sloppy lowering"],
    main: ["Chest-to-bar pull-ups", "High pull-ups"],
    acc: ["Pull-ups", "Straight bar dips"],
    yt: [["Explosive pull ups for muscle up"]],
  }),
  S("muscleup", "Muscle-up", "vpull", "B", {
    pre: ["explosivepu"],
    ttl: "2–6 months",
    muscles: "Lats, chest, triceps, shoulders",
    strain: "Elbows, wrists, shoulders",
    desc: "A pull-up that flows over the bar into a dip — from hanging below the bar to supporting above it.",
    steps: ["Use a slightly false or high grip.", "Pull explosively, towards the hips, slightly away from the bar.", "As the bar reaches the chest, lean over and drive the elbows up and forward (the transition).", "Press out of the dip to lockout."],
    good: ["Explosive pull", "Fast elbow turnover", "Strict lockout"],
    bad: ["Chicken-winging one arm over", "Too much kip", "Pulling straight up into the bar"],
    main: ["Muscle-ups", "Band-assisted muscle-ups", "Transition drills"],
    acc: ["Explosive pull-ups", "Straight bar dips"],
    yt: [["Muscle up tutorial step by step"]],
  }),
  S("archerpullup", "Archer Pull-up", "vpull", "B", {
    pre: ["pullup"],
    ttl: "2–4 months",
    muscles: "Lats, biceps (one side)",
    strain: "Elbows",
    desc: "A wide pull-up where you pull to one side while the other arm straightens — the bridge to the one-arm pull-up.",
    steps: ["Take a very wide grip.", "Pull towards one hand as the other arm straightens.", "Lower and switch sides.", "Slide the assisting hand along the bar as you get stronger."],
    good: ["Assisting arm straight", "Chin over the working hand", "Controlled"],
    bad: ["Bending both arms equally", "Swinging", "Partial range"],
    main: ["Archer pull-ups", "Typewriter pull-ups"],
    acc: ["Pull-ups", "One-arm hangs"],
    yt: [["Archer pull up tutorial"]],
  }),
  S("oapullup", "One-arm Pull-up", "vpull", "S", {
    pre: ["archerpullup"],
    ttl: "1–2+ years",
    muscles: "Lats, biceps, forearms, core",
    strain: "Elbows, shoulders",
    desc: "A full pull-up on one arm. One of the rarest strength skills.",
    steps: ["Build archer pull-ups and one-arm negatives.", "Hang on one arm, shoulder engaged.", "Pull with the body slightly turned towards the working arm.", "Chin over the bar, lower with control."],
    good: ["Engaged shoulder from the start", "Minimal rotation", "Full range"],
    bad: ["Hanging passively on the shoulder", "Big kip", "Uncontrolled drop"],
    main: ["One-arm negatives", "Assisted one-arm pull-ups"],
    acc: ["Archer pull-ups", "One-arm hangs"],
    yt: [["One arm pull up tutorial progression"]],
  }),

  /* ---------------- Core ---------------- */
  S("plank", "Plank", "core", "F", {
    hold: true,
    ttl: "a few days",
    muscles: "Abs, glutes, shoulders",
    strain: "Lower back",
    desc: "Holding a straight body on the forearms. The base of all core tension.",
    steps: ["Forearms under the shoulders, legs straight.", "Squeeze glutes and brace the stomach.", "Keep a straight line head to heels.", "Hold, breathing normally."],
    good: ["Straight line", "Glutes squeezed", "Neck neutral"],
    bad: ["Sagging hips", "Hips piked high", "Holding the breath"],
    main: ["Planks"],
    acc: ["Dead bugs", "Side plank"],
    yt: [["Proper plank form"]],
  }),
  S("hollow", "Hollow Body Hold", "core", "E", {
    pre: ["plank"],
    hold: true,
    ttl: "1–2 weeks",
    muscles: "Abs, hip flexors",
    strain: "Lower back",
    desc: "Lying on your back with the lower back pressed into the floor and arms and legs held just off it. The body shape used in almost every skill.",
    steps: ["Lie on your back, press the lower back into the floor.", "Lift the shoulders and legs a little off the floor.", "Reach the arms overhead by the ears.", "Bend the knees to make it easier."],
    good: ["Lower back flat to the floor", "Ribs pulled down", "Long body"],
    bad: ["Lower back arching up", "Legs too high", "Neck strained"],
    main: ["Hollow body holds", "Hollow rocks"],
    acc: ["Dead bugs", "Planks"],
    yt: [["Hollow body hold tutorial"]],
  }),
  S("kneeraise", "Hanging Knee Raise", "core", "F", {
    ttl: "~1 week",
    muscles: "Lower abs, hip flexors, grip",
    strain: "Shoulders",
    desc: "Hanging from a bar and lifting the knees to the chest without swinging.",
    steps: ["Dead hang, shoulders engaged.", "Lift the knees towards the chest, curling the pelvis up.", "Lower slowly.", "Stop the swing before the next rep."],
    good: ["Pelvis curls up", "No swing", "Slow lowering"],
    bad: ["Swinging for momentum", "Only lifting to hip height", "Dropping"],
    main: ["Hanging knee raises"],
    acc: ["Dead hang", "Lying leg raises"],
    yt: [["Hanging knee raise form"]],
  }),
  S("legraise", "Hanging Leg Raise", "core", "D", {
    pre: ["kneeraise"],
    ttl: "1–2 months",
    muscles: "Abs, hip flexors",
    strain: "Shoulders, lower back",
    desc: "Raising straight legs to horizontal or higher while hanging.",
    steps: ["Dead hang with engaged shoulders.", "Lift straight legs to at least horizontal.", "Lower slowly.", "Avoid swinging between reps."],
    good: ["Straight legs", "At least 90°", "No swing"],
    bad: ["Bent knees", "Momentum", "Arched back"],
    main: ["Hanging leg raises"],
    acc: ["Hanging knee raises", "Hollow body hold"],
    yt: [["Hanging leg raise tutorial"]],
  }),
  S("t2b", "Toes to Bar", "core", "C", {
    pre: ["legraise"],
    ttl: "1–2 months",
    muscles: "Abs, lats, hip flexors",
    strain: "Shoulders",
    desc: "Raising straight legs all the way to touch the bar, strictly.",
    steps: ["Hang, press the bar down slightly with straight arms.", "Raise straight legs past horizontal.", "Curl the hips up until the toes touch the bar.", "Lower with control."],
    good: ["Toes touch the bar", "Straight legs", "Controlled"],
    bad: ["Kipping", "Bending knees a lot", "Dropping"],
    main: ["Toes to bar"],
    acc: ["Hanging leg raises", "Hollow rocks"],
    yt: [["Strict toes to bar tutorial"]],
  }),
  S("wipers", "Windshield Wipers", "core", "B", {
    pre: ["t2b"],
    ttl: "2–3 months",
    muscles: "Obliques, abs, lats",
    strain: "Shoulders, lower back",
    desc: "Hanging with legs up at the bar and rotating them side to side like a car's wipers.",
    steps: ["Raise toes to the bar.", "Keep them there and rotate the legs to one side.", "Rotate through the middle to the other side.", "Keep the arms straight."],
    good: ["Legs stay high", "Controlled rotation", "Arms straight"],
    bad: ["Legs dropping", "Swinging", "Bent arms"],
    main: ["Hanging windshield wipers"],
    acc: ["Toes to bar", "Lying windshield wipers"],
    yt: [["Hanging windshield wipers tutorial"]],
  }),
  S("tucklsit", "Tuck L-sit", "core", "E", {
    pre: ["plank"],
    hold: true,
    ttl: "1–2 weeks",
    muscles: "Abs, hip flexors, triceps",
    strain: "Wrists",
    desc: "Supporting yourself on straight arms with the knees tucked to the chest and feet off the floor.",
    steps: ["Hands on parallettes or the floor beside the hips.", "Push down, lock the arms, depress the shoulders.", "Lift the feet and tuck the knees up.", "Hold."],
    good: ["Locked arms", "Shoulders pushed down", "Feet clear the floor"],
    bad: ["Shrugging", "Bent arms", "Leaning back"],
    main: ["Tuck L-sit holds"],
    acc: ["Support hold", "Hollow body hold"],
    yt: [["Tuck L sit tutorial"]],
  }),
  S("lsit", "L-sit", "core", "D", {
    pre: ["tucklsit"],
    hold: true,
    ttl: "1–2 months",
    muscles: "Abs, hip flexors, quads, triceps",
    strain: "Wrists",
    desc: "Supporting yourself on straight arms with straight legs held out in front, parallel to the floor.",
    steps: ["From a tuck L-sit, extend one leg, then both.", "Point the toes and lock the knees.", "Keep the shoulders pushed down.", "Hold."],
    good: ["Legs straight and level", "Arms locked", "Shoulders down"],
    bad: ["Legs drooping", "Bent knees", "Rounded, shrugged shoulders"],
    main: ["L-sit holds", "One-leg L-sit"],
    acc: ["Tuck L-sit", "Compression work"],
    yt: [["L sit tutorial beginners"]],
  }),
  S("dragonflag", "Dragon Flag", "core", "B", {
    pre: ["hollow", "legraise"],
    ttl: "2–4 months",
    muscles: "Abs, lats, whole core",
    strain: "Lower back, neck",
    desc: "Lying on a bench holding behind your head and lowering a rigid body with only the shoulders touching.",
    steps: ["Lie on a bench, grip behind the head.", "Lift the body up so only the upper back touches.", "Lower slowly as one straight line.", "Start with tucked or negative-only reps."],
    good: ["Body rigid and straight", "Slow lowering", "Hips don't bend"],
    bad: ["Piking at the hips", "Arching the lower back", "Dropping"],
    main: ["Dragon flag negatives", "Tuck dragon flags"],
    acc: ["Hollow body hold", "Hanging leg raises"],
    yt: [["Dragon flag tutorial progression"]],
  }),
  S("vsit", "V-sit", "core", "A", {
    pre: ["lsit"],
    hold: true,
    ttl: "6–12 months",
    muscles: "Abs, hip flexors, triceps, shoulders",
    strain: "Wrists, shoulders",
    desc: "An L-sit with the legs raised well above horizontal into a V. Needs strong compression and flexibility.",
    steps: ["From an L-sit, lean the shoulders back slightly.", "Raise the legs higher towards the face.", "Push the hands hard into the floor.", "Hold."],
    good: ["Legs above horizontal", "Locked arms", "Shoulders pushed down"],
    bad: ["Bent knees", "Collapsing on the hands", "Holding the breath"],
    main: ["V-sit holds", "High L-sit"],
    acc: ["L-sit", "Pike compression lifts"],
    yt: [["V sit tutorial progression"]],
  }),
  S("humanflag", "Human Flag", "core", "S", {
    pre: ["dragonflag"],
    hold: true,
    ttl: "6–12+ months",
    muscles: "Obliques, lats, shoulders",
    strain: "Shoulders, wrists",
    desc: "Holding your body out sideways from a vertical pole, like a flag.",
    steps: ["Grip a vertical pole, top hand pulling, bottom hand pushing.", "Lock both arms.", "Kick up and hold the body sideways (start tucked).", "Extend the legs over time."],
    good: ["Bottom arm locked and pushing", "Hips stacked", "Body straight"],
    bad: ["Bent bottom arm", "Hips sagging", "Hands too close"],
    main: ["Tuck human flag", "Vertical flag"],
    acc: ["Side plank", "Dragon flag"],
    yt: [["Human flag tutorial progression"]],
  }),

  /* ---------------- Legs ---------------- */
  S("squat", "Bodyweight Squat", "legs", "F", {
    ttl: "a few days",
    muscles: "Quads, glutes",
    strain: "Knees",
    desc: "Sitting down and standing up with only your bodyweight. The base of leg training.",
    steps: ["Feet shoulder-width, toes slightly out.", "Sit back and down, knees following the toes.", "Go until the thighs are at least parallel.", "Stand tall, squeezing the glutes."],
    good: ["Heels stay down", "Knees track over toes", "Chest up"],
    bad: ["Knees caving in", "Heels lifting", "Half depth"],
    main: ["Bodyweight squats"],
    acc: ["Glute bridges", "Wall sits"],
    yt: [["Bodyweight squat proper form"]],
  }),
  S("splitsquat", "Split Squat", "legs", "E", {
    pre: ["squat"],
    ttl: "1–2 weeks",
    muscles: "Quads, glutes",
    strain: "Knees",
    desc: "A static lunge: one foot forward, one back, lowering straight down.",
    steps: ["Step one foot forward into a long stance.", "Lower the back knee towards the floor.", "Front shin roughly vertical.", "Drive up through the front foot."],
    good: ["Torso upright", "Front heel down", "Back knee near the floor"],
    bad: ["Front knee caving", "Leaning forward too much", "Short range"],
    main: ["Split squats", "Reverse lunges"],
    acc: ["Squats", "Calf raises"],
    yt: [["Split squat form tutorial"]],
  }),
  S("jumpsquat", "Jump Squat", "legs", "E", {
    pre: ["squat"],
    ttl: "1–2 weeks",
    muscles: "Quads, glutes, calves",
    strain: "Knees, ankles",
    desc: "A squat that ends in a jump, with a soft landing. Builds power.",
    steps: ["Squat to about parallel.", "Explode up and leave the floor.", "Land softly on the balls of the feet into the next squat.", "Reset if form breaks."],
    good: ["Soft, quiet landing", "Knees over toes", "Full extension in the air"],
    bad: ["Landing stiff-legged", "Knees caving", "Rushing sloppy reps"],
    main: ["Jump squats"],
    acc: ["Squats", "Calf raises"],
    yt: [["Jump squat form"]],
  }),
  S("bss", "Bulgarian Split Squat", "legs", "D", {
    pre: ["splitsquat"],
    ttl: "2–4 weeks",
    muscles: "Quads, glutes",
    strain: "Knees, hip flexors",
    desc: "A split squat with the back foot raised on a bench — much more load on the front leg.",
    steps: ["Back foot laces-down on a bench.", "Front foot far enough forward to sink straight down.", "Lower until the back knee nearly touches.", "Drive up through the front heel."],
    good: ["Balanced, upright", "Front knee tracks over toes", "Full depth"],
    bad: ["Front foot too close", "Bouncing", "Knee caving"],
    main: ["Bulgarian split squats"],
    acc: ["Split squats", "Glute bridges"],
    yt: [["Bulgarian split squat tutorial"]],
  }),
  S("sissy", "Sissy Squat", "legs", "C", {
    pre: ["splitsquat"],
    ttl: "1–2 months",
    muscles: "Quads (especially the knee end)",
    strain: "Knees",
    desc: "Leaning back while the knees travel far forward, heels up. Hits the quads very hard.",
    steps: ["Hold a support for balance, rise onto the toes.", "Push the knees forward while leaning the torso back.", "Keep hips and torso in line.", "Lower as far as comfortable, then return."],
    good: ["Straight line knees to shoulders", "Controlled", "Hold a support at first"],
    bad: ["Bending at the hips", "Dropping fast", "Forcing painful range"],
    main: ["Assisted sissy squats"],
    acc: ["Split squats", "Wall sits"],
    yt: [["Sissy squat tutorial"]],
  }),
  S("assistedpistol", "Assisted Pistol Squat", "legs", "C", {
    pre: ["bss"],
    ttl: "1–2 months",
    muscles: "Quads, glutes, balance",
    strain: "Knees",
    desc: "A one-leg squat holding a pole or doorframe, or sitting to a box.",
    steps: ["Stand on one leg, the other straight in front.", "Hold a support lightly.", "Squat as deep as you can on one leg.", "Stand back up, using the support as little as possible."],
    good: ["Heel stays down", "Knee over toes", "Deep and controlled"],
    bad: ["Pulling yourself up with the arms", "Heel lifting", "Collapsing at the bottom"],
    main: ["Assisted pistols", "Box pistols"],
    acc: ["Bulgarian split squats", "Ankle mobility"],
    yt: [["Assisted pistol squat progression"]],
  }),
  S("pistol", "Pistol Squat", "legs", "B", {
    pre: ["assistedpistol"],
    ttl: "2–4 months",
    muscles: "Quads, glutes, core",
    strain: "Knees, ankles",
    desc: "A full one-leg squat with the other leg held straight out in front.",
    steps: ["Stand on one leg, the other leg straight forward, arms out.", "Sit down on one leg until the hamstring meets the calf.", "Keep the free leg off the floor.", "Stand back up without help."],
    good: ["Full depth", "Heel down", "Free leg kept up"],
    bad: ["Knee caving in", "Rounding and collapsing", "Bouncing"],
    main: ["Pistol squats"],
    acc: ["Assisted pistols", "L-sit (for the free leg)"],
    yt: [["Pistol squat tutorial"]],
  }),
  S("shrimp", "Shrimp Squat", "legs", "B", {
    pre: ["bss"],
    ttl: "2–4 months",
    muscles: "Quads, glutes",
    strain: "Knees",
    desc: "A one-leg squat holding the back foot behind you, touching the back knee to the floor.",
    steps: ["Stand on one leg, hold the other foot behind you.", "Lower until the back knee touches the floor.", "Lean forward slightly for balance.", "Stand back up."],
    good: ["Back knee touches lightly", "Controlled", "Standing leg tracks well"],
    bad: ["Crashing the knee down", "Front knee caving", "Rushing"],
    main: ["Shrimp squats", "Assisted shrimp squats"],
    acc: ["Bulgarian split squats", "Reverse lunges"],
    yt: [["Shrimp squat tutorial"]],
  }),
  S("glutebridge", "Glute Bridge", "legs", "F", {
    ttl: "a few days",
    muscles: "Glutes, hamstrings",
    strain: "Lower back",
    desc: "Lying on your back, knees bent, lifting the hips up by squeezing the glutes.",
    steps: ["Lie on your back, feet flat, knees bent.", "Push through the heels and lift the hips.", "Squeeze the glutes at the top.", "Lower slowly."],
    good: ["Straight line knees to shoulders at the top", "Glutes squeezed", "Ribs down"],
    bad: ["Arching the lower back", "Pushing through the toes", "Rushing"],
    main: ["Glute bridges"],
    acc: ["Planks", "Squats"],
    yt: [["Glute bridge form"]],
  }),
  S("slbridge", "Single-leg Glute Bridge", "legs", "E", {
    pre: ["glutebridge"],
    ttl: "1–2 weeks",
    muscles: "Glutes, hamstrings",
    strain: "Lower back",
    desc: "A glute bridge on one leg — twice the load and more balance.",
    steps: ["One foot flat, the other leg straight up or out.", "Lift the hips by pushing through one heel.", "Keep the hips level.", "Lower with control."],
    good: ["Level hips", "Full hip extension", "Heel driving"],
    bad: ["Hips tilting", "Arching", "Short range"],
    main: ["Single-leg glute bridges"],
    acc: ["Glute bridges", "Hip thrusts"],
    yt: [["Single leg glute bridge form"]],
  }),
  S("nordicneg", "Nordic Curl Negative", "legs", "C", {
    pre: ["slbridge"],
    ttl: "1–2 months",
    muscles: "Hamstrings",
    strain: "Hamstrings, knees",
    desc: "Kneeling with the ankles held, lowering your body forward as slowly as possible using only the hamstrings.",
    steps: ["Kneel on a pad, ankles anchored under something solid.", "Keep a straight line knees to head.", "Lower forward as slowly as you can.", "Catch yourself with the hands and push back up."],
    good: ["Hips stay extended", "Very slow descent", "Hands ready to catch"],
    bad: ["Bending at the hips", "Dropping fast", "No padding"],
    main: ["Nordic negatives"],
    acc: ["Single-leg bridges", "Romanian deadlifts"],
    yt: [["Nordic hamstring curl progression"]],
  }),
  S("nordic", "Nordic Curl", "legs", "A", {
    pre: ["nordicneg"],
    ttl: "6–12 months",
    muscles: "Hamstrings",
    strain: "Hamstrings, knees",
    desc: "Lowering all the way down and pulling yourself back up with the hamstrings alone.",
    steps: ["Set up as for negatives.", "Lower under control to the floor.", "Pull back up using the hamstrings without pushing off.", "Keep the hips straight."],
    good: ["Hips extended throughout", "Full range both ways", "Controlled"],
    bad: ["Hip hinge to cheat", "Pushing up with the hands", "Rushing"],
    main: ["Nordic curls"],
    acc: ["Nordic negatives", "Glute-ham raises"],
    yt: [["Full nordic curl tutorial"]],
  }),
];

export const SKILL = Object.fromEntries(SKILLS.map((s) => [s.id, s]));
export const childrenOf = (id) => SKILLS.filter((s) => s.pre.includes(id));
export const catLabel = (id) => CATEGORIES.find((c) => c.id === id)?.label || id;

// Status from your best set: reps for movement skills, seconds for holds.
export function levelFor(skill, best) {
  if (!best) return LEVELS[0];
  const v = skill.hold ? best.hold : best.reps;
  let lv = LEVELS[0];
  for (const L of LEVELS) if (v >= (skill.hold ? L.hold : L.reps) && (skill.hold ? L.hold : L.reps) > 0) lv = L;
  return lv;
}

// Next goal for a skill at a given level.
export function nextTarget(skill, level) {
  const i = LEVELS.findIndex((l) => l.id === level.id);
  const next = LEVELS[Math.min(LEVELS.length - 1, i + 1)];
  if (level.id === "mastered") return null;
  return skill.hold ? `${next.hold} s hold` : `${next.reps} rep${next.reps === 1 ? "" : "s"}`;
}

// Base (start of the chain) and target (hardest skill this one leads to),
// like the WINGS progressions row.
const rank = (s) => DIFFICULTY.indexOf(s.diff);
const reachCache = {};
function reach(s) {
  // Hardest difficulty reachable from s (s itself or anything after it).
  if (reachCache[s.id] != null) return reachCache[s.id];
  return (reachCache[s.id] = Math.max(rank(s), ...childrenOf(s.id).map(reach)));
}
const bestChild = (s) => childrenOf(s.id).sort((a, b) => reach(b) - reach(a) || rank(a) - rank(b))[0] || null;
export function chain(skill) {
  const reg = skill.pre[0] ? SKILL[skill.pre[0]] : null;
  let base = reg;
  while (base?.pre[0]) base = SKILL[base.pre[0]];
  const prog = bestChild(skill);
  let target = prog;
  for (let guard = 0; target && guard < 30; guard++) {
    const next = bestChild(target);
    if (!next) break;
    target = next;
  }
  return { base: base && base.id !== reg?.id ? base : null, reg, prog, target: target && target.id !== prog?.id ? target : null };
}

// Tree layout per category: row = longest prerequisite chain (0 = easiest),
// x = average of the prerequisites' x, then pushed apart so nodes never overlap.
export function layout(cat) {
  const list = SKILLS.filter((s) => s.cat === cat);
  const depth = {};
  const d = (s) => (depth[s.id] ??= s.pre.length ? 1 + Math.max(...s.pre.map((p) => d(SKILL[p]))) : 0);
  list.forEach(d);
  const rows = [];
  for (const s of list) (rows[depth[s.id]] ||= []).push(s);
  const x = {};
  rows.forEach((row, r) => {
    if (r === 0) {
      // Roots: spread out, ordered so that roots sharing children sit together.
      row.forEach((s, i) => (x[s.id] = i * 1.6));
      return;
    }
    const want = (s) => s.pre.reduce((a, p) => a + x[p], 0) / s.pre.length;
    row.sort((a, b) => want(a) - want(b));
    let prev = -Infinity;
    const placed = row.map((s) => {
      const v = Math.max(want(s), prev + 1);
      prev = v;
      return v;
    });
    // Re-centre the row on what it wanted.
    const shift = (row.reduce((a, s) => a + want(s), 0) - placed.reduce((a, v) => a + v, 0)) / row.length;
    row.forEach((s, i) => (x[s.id] = placed[i] + shift));
  });
  const xs = Object.values(x);
  const min = Math.min(...xs);
  for (const k in x) x[k] -= min;
  return { rows, depth, x, width: Math.max(...xs) - min + 1, height: rows.length };
}
